/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

module decoder_3to8(clk, rst_n, s0, s1, s2, y0, y1, y2, y3, y4, y5, y6, y7);
  wire _00_;
  wire _01_;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  wire rst_n_i;
  wire rst_n_s2;
  input s0;
  wire s0;
  input s1;
  wire s1;
  input s2;
  wire s2;
  output y0;
  wire y0;
  wire y0_int;
  output y1;
  wire y1;
  wire y1_int;
  output y2;
  wire y2;
  wire y2_int;
  output y3;
  wire y3;
  wire y3_int;
  output y4;
  wire y4;
  wire y4_int;
  output y5;
  wire y5;
  wire y5_int;
  output y6;
  wire y6;
  wire y6_int;
  output y7;
  wire y7;
  wire y7_int;
  INV _02_ (
    .A(s1),
    .Y(_00_)
  );
  INV _03_ (
    .A(s0),
    .Y(_01_)
  );
  NOR3 _04_ (
    .A(s2),
    .B(s1),
    .C(s0),
    .Y(y0)
  );
  NOR3 _05_ (
    .A(s2),
    .B(s1),
    .C(_01_),
    .Y(y1)
  );
  NOR3 _06_ (
    .A(s2),
    .B(_00_),
    .C(s0),
    .Y(y2)
  );
  NOR3 _07_ (
    .A(s2),
    .B(_00_),
    .C(_01_),
    .Y(y3)
  );
  AND3 _08_ (
    .A(s2),
    .B(_00_),
    .C(_01_),
    .Y(y4)
  );
  AND3 _09_ (
    .A(s2),
    .B(_00_),
    .C(s0),
    .Y(y5)
  );
  AND3 _10_ (
    .A(s2),
    .B(s1),
    .C(_01_),
    .Y(y6)
  );
  AND3 _11_ (
    .A(s2),
    .B(s1),
    .C(s0),
    .Y(y7)
  );
  assign rst_n_i = rst_n_s2;
  assign y0_int = y0;
  assign y1_int = y1;
  assign y2_int = y2;
  assign y3_int = y3;
  assign y4_int = y4;
  assign y5_int = y5;
  assign y6_int = y6;
  assign y7_int = y7;
endmodule
