/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

module traffic_light(clk, rst_n, go, emergency, red, green, amber);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  output amber;
  wire amber;
  wire amber_int;
  input clk;
  wire clk;
  input emergency;
  wire emergency;
  wire emergency_i;
  reg emergency_s1;
  reg emergency_s2;
  input go;
  wire go;
  wire go_i;
  reg go_s1;
  reg go_s2;
  output green;
  wire green;
  wire green_int;
  wire next_AMBER;
  wire next_GREEN;
  wire next_RED;
  output red;
  wire red;
  wire red_int;
  input rst_n;
  wire rst_n;
  wire rst_n_i;
  reg rst_n_s1;
  reg rst_n_s2;
  wire set_feedback;
  reg state_AMBER;
  reg state_GREEN;
  reg state_RED;
  wire state_active;
  wire t_0;
  wire t_1;
  wire t_2;
  wire t_3;
  wire t_4;
  always @(posedge clk, negedge rst_n_s2)
    if (!rst_n_s2) state_RED <= 1'h0;
    else state_RED <= _00_;
  always @(posedge clk, negedge rst_n_s2)
    if (!rst_n_s2) state_GREEN <= 1'h0;
    else state_GREEN <= next_GREEN;
  always @(posedge clk, negedge rst_n_s2)
    if (!rst_n_s2) state_AMBER <= 1'h0;
    else state_AMBER <= next_AMBER;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rst_n_s1 <= 1'h0;
    else rst_n_s1 <= 1'h1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rst_n_s2 <= 1'h0;
    else rst_n_s2 <= rst_n_s1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) emergency_s1 <= 1'h0;
    else emergency_s1 <= emergency;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) emergency_s2 <= 1'h0;
    else emergency_s2 <= emergency_s1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) go_s1 <= 1'h0;
    else go_s1 <= go;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) go_s2 <= 1'h0;
    else go_s2 <= go_s1;
  assign _04_ = ~go_s2;
  assign _03_ = ~emergency_s2;
  assign set_feedback = ~state_active;
  assign _01_ = go_s2 & _03_;
  assign t_0 = state_RED & _01_;
  assign _05_ = _04_ | emergency_s2;
  assign t_1 = state_RED & _05_;
  assign _06_ = go_s2 | emergency_s2;
  assign next_AMBER = state_GREEN & _06_;
  assign _02_ = _04_ & _03_;
  assign t_3 = state_GREEN & _02_;
  assign next_RED = t_1 | state_AMBER;
  assign next_GREEN = t_0 | t_3;
  assign _07_ = state_RED | state_GREEN;
  assign state_active = _07_ | state_AMBER;
  assign _00_ = next_RED | set_feedback;
  assign amber = state_AMBER;
  assign amber_int = state_AMBER;
  assign emergency_i = emergency_s2;
  assign go_i = go_s2;
  assign green = state_GREEN;
  assign green_int = state_GREEN;
  assign red = state_RED;
  assign red_int = state_RED;
  assign rst_n_i = rst_n_s2;
  assign t_2 = next_AMBER;
  assign t_4 = state_AMBER;
endmodule
