/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

module property_violating(clk, rst_n, x, enable, fault);
  wire _00_;
  wire _01_;
  input clk;
  wire clk;
  output enable;
  wire enable;
  wire enable_int;
  output fault;
  wire fault;
  wire fault_int;
  wire next_A;
  wire next_B;
  input rst_n;
  wire rst_n;
  wire rst_n_i;
  reg rst_n_s1;
  reg rst_n_s2;
  wire set_feedback;
  reg state_A;
  reg state_B;
  wire state_active;
  wire t_0;
  wire t_1;
  wire t_2;
  wire t_3;
  input x;
  wire x;
  always @(posedge clk, negedge rst_n_s2)
    if (!rst_n_s2) state_A <= 1'h0;
    else state_A <= _00_;
  always @(posedge clk, negedge rst_n_s2)
    if (!rst_n_s2) state_B <= 1'h0;
    else state_B <= next_B;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rst_n_s1 <= 1'h0;
    else rst_n_s1 <= 1'h1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rst_n_s2 <= 1'h0;
    else rst_n_s2 <= rst_n_s1;
  assign set_feedback = ~state_active;
  assign _01_ = ~x;
  assign t_2 = state_B & _01_;
  assign t_3 = state_B & x;
  assign next_A = t_1 | t_2;
  assign next_B = t_0 | t_3;
  assign state_active = state_A | state_B;
  assign _00_ = next_A | set_feedback;
  assign t_0 = state_A & x;
  assign t_1 = state_A & _01_;
  assign enable = state_B;
  assign enable_int = state_B;
  assign fault = state_B;
  assign fault_int = state_B;
  assign rst_n_i = rst_n_s2;
endmodule
