"""C2 ``cells_sim.v`` — behavioural Verilog models of the G- and F-cells.

[R4-17]: exhaustive simulation (§C4.3) runs the mapped netlist under Icarus
Verilog, which can read neither Yosys JSON nor the Liberty file — so without
this file there is literally nothing to simulate.  C2 therefore emits Verilog
models for the same G- and F-cells it writes to ``cells.lib``, generated from
the *same* ``parts.csv`` functions and the *same* ``_FLOP_SPECS`` truth, so the
two artefacts cannot drift.

M-cell models live under ``gatepack/macros/`` and are concatenated onto this
file by the build; they are the same files C4 uses for equivalence (§19 R25).
"""

from __future__ import annotations

from typing import Sequence

from gatepack import parts as parts_mod
from gatepack.liberty import boolean
from gatepack.liberty.generator import OUTPUT_PIN, _FLOP_SPECS
from gatepack.parts import Part


def generate(
    parts: Sequence[Part],
    project_vcc: float = parts_mod.DEFAULT_VCC,
    allow_single_source: bool = False,
) -> str:
    """Emit ``cells_sim.v`` for the G- and F-cells eligible for the Liberty file.

    Uses the same ``select_for_liberty`` selection as the Liberty generator, so
    the set of modelled cells equals the set of inference targets exactly.
    """
    included, _ = parts_mod.select_for_liberty(
        parts, project_vcc=project_vcc, allow_single_source=allow_single_source
    )
    # One module per distinct cell. Duplicate module definitions are a hard
    # error in Icarus, so without this the equivalence and exhaustive-
    # simulation checks both fail the moment a library offers the same
    # function in two package sizes (see parts.representative_parts).
    included = parts_mod.representative_parts(included)

    blocks = [_cell_model(part) for part in included]
    header = [
        "// Generated by gatepack (C2) — behavioural models for Icarus (§C4.3).",
        "// Do not edit. The M-cell models are appended from gatepack/macros/.",
        "`timescale 1ns/1ps",
        "",
    ]
    return "\n".join(header + blocks)


def _cell_model(part: Part) -> str:
    if part.tier == "G":
        return _g_cell_model(part)
    if part.tier == "F":
        return _f_cell_model(part)
    raise ValueError(f"{part.cell}: tier {part.tier!r} has no sim model")


def _g_cell_model(part: Part) -> str:
    func = boolean.translate_verilog(part.function or "", part.inputs)
    pins = boolean.pin_names(part.inputs)
    ports = [f"input wire {name}" for name in pins] + [f"output wire {OUTPUT_PIN}"]
    return (
        f"module {part.cell} (\n"
        + ",\n".join(f"  {p}" for p in ports)
        + "\n);\n"
        + f"  assign {OUTPUT_PIN} = {func};\n"
        + "endmodule\n"
    )


def _parse_control(expr: str, reset_value: int) -> tuple[str, bool, int]:
    """Return ``(pin, active_high, value)`` for a ``clear``/``preset`` expression.

    ``expr`` is either ``PIN`` (asserted high) or ``!PIN`` (asserted low); the
    asserted value is ``reset_value`` (0 for clear, 1 for preset).
    """
    expr = expr.strip()
    active_high = True
    if expr.startswith("!"):
        active_high = False
        expr = expr[1:]
    return expr, active_high, reset_value


def _f_cell_model(part: Part) -> str:
    spec = _FLOP_SPECS.get(part.cell)
    if spec is None:
        raise ValueError(
            f"{part.cell}: unsupported F-cell (supported: {sorted(_FLOP_SPECS)})"
        )
    clock = spec["clock"]  # type: str
    d_pin = spec["next_state"]  # type: str
    pins = list(spec["pins"])  # type: list[str]

    controls: list[tuple[str, bool, int]] = []
    if "clear" in spec:
        controls.append(_parse_control(spec["clear"], 0))
    if "preset" in spec:
        controls.append(_parse_control(spec["preset"], 1))
    # clear dominates preset, matching the Liberty clear_preset_var1/var2 fix.

    ports = [f"input wire {name}" for name in pins] + ["output reg Q"]
    lines = [
        f"module {part.cell} (",
        ",\n".join(f"  {p}" for p in ports),
        ");",
    ]

    events = [f"posedge {clock}"]
    for pin, active_high, _value in controls:
        events.append(f"{'posedge' if active_high else 'negedge'} {pin}")

    lines.append(f"  always @({' or '.join(events)}) begin")
    if controls:
        first = True
        for pin, active_high, value in controls:
            cond = f"{pin}" if active_high else f"!{pin}"
            kw = "if" if first else "else if"
            lines.append(f"    {kw} ({cond}) Q <= 1'b{value};")
            first = False
        lines.append(f"    else Q <= {d_pin};")
    else:
        lines.append(f"    Q <= {d_pin};")
    lines.append("  end")
    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)
