/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

module vacuous_mutex(clk, rst_n, x, a, b);
  wire _00_;
  wire _01_;
  output a;
  wire a;
  wire a_int;
  output b;
  wire b;
  wire b_int;
  input clk;
  wire clk;
  wire next_A;
  wire next_B;
  input rst_n;
  wire rst_n;
  wire rst_n_i;
  reg rst_n_s1;
  reg rst_n_s2;
  wire set_feedback;
  reg state_A;
  reg state_B;
  wire state_active;
  wire t_0;
  wire t_1;
  wire t_2;
  input x;
  wire x;
  always @(posedge clk, negedge rst_n_s2)
    if (!rst_n_s2) state_A <= 1'h0;
    else state_A <= _00_;
  always @(posedge clk, negedge rst_n_s2)
    if (!rst_n_s2) state_B <= 1'h0;
    else state_B <= next_B;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rst_n_s1 <= 1'h0;
    else rst_n_s1 <= 1'h1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rst_n_s2 <= 1'h0;
    else rst_n_s2 <= rst_n_s1;
  assign _01_ = ~x;
  assign set_feedback = ~state_active;
  assign _00_ = next_A | set_feedback;
  assign next_B = state_A & x;
  assign t_1 = state_A & _01_;
  assign next_A = t_1 | state_B;
  assign state_active = state_A | state_B;
  assign a = state_B;
  assign a_int = state_B;
  assign b = 1'h0;
  assign b_int = 1'h0;
  assign rst_n_i = rst_n_s2;
  assign t_0 = next_B;
  assign t_2 = state_B;
endmodule
