// Generated by gatepack (C1). Do not edit.
`timescale 1ns/1ps

(* gp_src = "decoder_3to8.yaml:1:name" *)
module decoder_3to8 (
  input wire clk,
  input wire rst_n,
  input wire s0,
  input wire s1,
  input wire s2,
  output wire y0,
  output wire y1,
  output wire y2,
  output wire y3,
  output wire y4,
  output wire y5,
  output wire y6,
  output wire y7
);


  // reset: async assert, sync de-assert (§9.3)
  (* gp_src = "decoder_3to8.yaml:4:reset" *)
  reg rst_n_s1;
  (* gp_src = "decoder_3to8.yaml:4:reset" *)
  reg rst_n_s2;
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rst_n_s1 <= 1'b0;
      rst_n_s2 <= 1'b0;
    end else begin
      rst_n_s1 <= 1'b1;
      rst_n_s2 <= rst_n_s1;
    end
  end
  wire rst_n_i = rst_n_s2;

  // --- one-hot state register (§6.2): the flop output IS the state ---
  (* gp_src = "decoder_3to8.yaml:19:states" *)
  reg state_S0;
  (* gp_src = "decoder_3to8.yaml:22:transitions[0]" *)
  wire t_0 = (state_S0 & 1'b1);
  (* gp_src = "decoder_3to8.yaml:19:states" *)
  wire next_S0 = t_0;
  (* gp_src = "decoder_3to8.yaml:19:states" *)
  wire state_active = (state_S0);
  (* gp_src = "decoder_3to8.yaml:19:states" *)
  wire set_feedback = ~state_active;
  always @(posedge clk or negedge rst_n_i) begin
    if (!rst_n_i) begin
      state_S0 <= 1'b0;
    end else begin
      state_S0 <= next_S0 | set_feedback;
    end
  end

  (* gp_src = "decoder_3to8.yaml:24:output_logic.y0" *)
  wire y0_int = (((~s0) & (~s1)) & (~s2));
  assign y0 = y0_int;
  (* gp_src = "decoder_3to8.yaml:25:output_logic.y1" *)
  wire y1_int = ((s0 & (~s1)) & (~s2));
  assign y1 = y1_int;
  (* gp_src = "decoder_3to8.yaml:26:output_logic.y2" *)
  wire y2_int = (((~s0) & s1) & (~s2));
  assign y2 = y2_int;
  (* gp_src = "decoder_3to8.yaml:27:output_logic.y3" *)
  wire y3_int = ((s0 & s1) & (~s2));
  assign y3 = y3_int;
  (* gp_src = "decoder_3to8.yaml:28:output_logic.y4" *)
  wire y4_int = (((~s0) & (~s1)) & s2);
  assign y4 = y4_int;
  (* gp_src = "decoder_3to8.yaml:29:output_logic.y5" *)
  wire y5_int = ((s0 & (~s1)) & s2);
  assign y5 = y5_int;
  (* gp_src = "decoder_3to8.yaml:30:output_logic.y6" *)
  wire y6_int = (((~s0) & s1) & s2);
  assign y6 = y6_int;
  (* gp_src = "decoder_3to8.yaml:31:output_logic.y7" *)
  wire y7_int = ((s0 & s1) & s2);
  assign y7 = y7_int;
endmodule
