"""Contract tests for ``gatepack analyse`` (§17, app/shared/api.ts).

``analyse <dir> --json`` must emit the standard ``ok``/``schema`` envelope whose
``data`` is the ``AnalysisSummary``; a directory with no mapped netlist must be
an explicit ``ok: false`` error envelope, never a summary of zeros.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
LIBRARY_CSV = REPO / "libraries" / "74aup.csv"

LIBERTY = """/* Generated by gatepack (C2). */
library (gatepack) {
  cell (INV) {
    area : 1.0;
    pin(A) {
      direction : input;
      capacitance : 0.0;
    }
    pin(Y) {
      direction : output;
      function : "(!A)";
    }
  }
}
"""

MAPPED = (
    '{"modules": {"t": {'
    '"ports": {"x": {"direction": "input", "bits": [2]},'
    '          "y": {"direction": "output", "bits": [4]}},'
    '"cells": {'
    '"$1": {"type": "INV", "port_directions": {"A": "input", "Y": "output"},'
    '"connections": {"A": [2], "Y": [4]}}'
    "},"
    '"netnames": {"x": {"bits": [2]}, "y": {"bits": [4]}}'
    "}}}"
)


def _run(*argv: str, cwd: Path | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "gatepack.cli", *argv],
        cwd=str(cwd or REPO),
        capture_output=True,
        text=True,
    )


def _envelope(proc: subprocess.CompletedProcess) -> dict:
    assert proc.stdout.strip(), f"empty stdout; stderr={proc.stderr}"
    return json.loads(proc.stdout)


def _out_dir(tmp_path: Path, *, mapped: bool = True) -> Path:
    out = tmp_path / "out"
    out.mkdir()
    if mapped:
        (out / "mapped.json").write_text(MAPPED)
    (out / "cells.lib").write_text(LIBERTY)
    return out


def test_analyse_json_envelope(tmp_path):
    out = _out_dir(tmp_path)
    proc = _run("analyse", str(out), "--json")
    assert proc.returncode == 0, proc.stderr
    env = _envelope(proc)
    assert env["ok"] is True
    assert env["command"] == "analyse"
    assert env["schema"] == 1
    assert env["warnings"] == []
    data = env["data"]
    assert set(data) == {"metrics", "scoap", "faults", "cpldBlockers"}
    for metric in data["metrics"]:
        assert set(metric) == {"name", "value", "unit", "limit", "violated"}
        assert isinstance(metric["violated"], bool)
    assert set(data["faults"]) == {"detected", "undetected", "redundant", "untestable"}
    for s in data["scoap"]:
        assert set(s) == {"net", "controllability0", "controllability1", "observability"}


def test_analyse_missing_mapped_netlist_is_error_not_zeros(tmp_path):
    out = _out_dir(tmp_path, mapped=False)
    proc = _run("analyse", str(out), "--json")
    assert proc.returncode == 1
    env = _envelope(proc)
    assert env["ok"] is False
    assert env["command"] == "analyse"
    assert env["error"]["severity"] == "error"
    assert "mapped netlist" in env["error"]["message"]
    # never a fabricated all-zeros summary
    assert "data" not in env
    assert "error:" in proc.stderr


def test_analyse_exits_error_on_missing_netlist_human(tmp_path):
    out = _out_dir(tmp_path, mapped=False)
    proc = _run("analyse", str(out))
    assert proc.returncode == 1
    assert "mapped netlist" in proc.stderr


def test_analyse_stdout_is_exactly_one_object(tmp_path):
    out = _out_dir(tmp_path)
    proc = _run("analyse", str(out), "--json")
    stripped = proc.stdout.strip()
    assert stripped.count("\n") == 0
    json.loads(stripped)
