/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

module traffic_light(clk, rst_n, go, emergency, red, green, amber);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  output amber;
  wire amber;
  wire amber_int;
  input clk;
  wire clk;
  input emergency;
  wire emergency;
  wire emergency_i;
  wire emergency_s1;
  wire emergency_s2;
  input go;
  wire go;
  wire go_i;
  wire go_s1;
  wire go_s2;
  output green;
  wire green;
  wire green_int;
  wire next_AMBER;
  wire next_GREEN;
  output red;
  wire red;
  wire red_int;
  input rst_n;
  wire rst_n;
  wire rst_n_i;
  wire rst_n_s1;
  wire rst_n_s2;
  wire state_AMBER;
  wire state_GREEN;
  wire state_RED;
  wire t_2;
  wire t_4;
  INV _09_ (
    .A(emergency_s2),
    .Y(_08_)
  );
  INV _10_ (
    .A(state_RED),
    .Y(_01_)
  );
  NOR2 _11_ (
    .A(go_s2),
    .B(emergency_s2),
    .Y(_02_)
  );
  OR2 _12_ (
    .A(go_s2),
    .B(emergency_s2),
    .Y(_03_)
  );
  AND2 _13_ (
    .A(state_GREEN),
    .B(_03_),
    .Y(next_AMBER)
  );
  NAND3 _14_ (
    .A(go_s2),
    .B(_08_),
    .C(state_RED),
    .Y(_04_)
  );
  NAND2 _15_ (
    .A(state_GREEN),
    .B(_02_),
    .Y(_05_)
  );
  NAND2 _16_ (
    .A(_04_),
    .B(_05_),
    .Y(next_GREEN)
  );
  NAND2 _17_ (
    .A(_01_),
    .B(state_GREEN),
    .Y(_06_)
  );
  AND2 _18_ (
    .A(_04_),
    .B(_06_),
    .Y(_07_)
  );
  OR2 _19_ (
    .A(state_AMBER),
    .B(_07_),
    .Y(_00_)
  );
  DFF_R _20_ (
    .CK(clk),
    .D(_00_),
    .Q(state_RED),
    .RST_N(rst_n_s2)
  );
  DFF_R _21_ (
    .CK(clk),
    .D(next_GREEN),
    .Q(state_GREEN),
    .RST_N(rst_n_s2)
  );
  DFF_R _22_ (
    .CK(clk),
    .D(next_AMBER),
    .Q(state_AMBER),
    .RST_N(rst_n_s2)
  );
  DFF_R _23_ (
    .CK(clk),
    .D(1'h1),
    .Q(rst_n_s1),
    .RST_N(rst_n)
  );
  DFF_R _24_ (
    .CK(clk),
    .D(rst_n_s1),
    .Q(rst_n_s2),
    .RST_N(rst_n)
  );
  DFF_R _25_ (
    .CK(clk),
    .D(emergency),
    .Q(emergency_s1),
    .RST_N(rst_n)
  );
  DFF_R _26_ (
    .CK(clk),
    .D(emergency_s1),
    .Q(emergency_s2),
    .RST_N(rst_n)
  );
  DFF_R _27_ (
    .CK(clk),
    .D(go),
    .Q(go_s1),
    .RST_N(rst_n)
  );
  DFF_R _28_ (
    .CK(clk),
    .D(go_s1),
    .Q(go_s2),
    .RST_N(rst_n)
  );
  assign amber = state_AMBER;
  assign amber_int = state_AMBER;
  assign emergency_i = emergency_s2;
  assign go_i = go_s2;
  assign green = state_GREEN;
  assign green_int = state_GREEN;
  assign red = state_RED;
  assign red_int = state_RED;
  assign rst_n_i = rst_n_s2;
  assign t_2 = next_AMBER;
  assign t_4 = state_AMBER;
endmodule
