// Generated by gatepack (C1). Do not edit.
`timescale 1ns/1ps

(* gp_src = "vacuous_mutex.yaml:5:name" *)
module vacuous_mutex (
  input wire clk,
  input wire rst_n,
  input wire x,
  output wire a,
  output wire b
);


  // reset: async assert, sync de-assert (§9.3)
  (* gp_src = "vacuous_mutex.yaml:8:reset" *)
  reg rst_n_s1;
  (* gp_src = "vacuous_mutex.yaml:8:reset" *)
  reg rst_n_s2;
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rst_n_s1 <= 1'b0;
      rst_n_s2 <= 1'b0;
    end else begin
      rst_n_s1 <= 1'b1;
      rst_n_s2 <= rst_n_s1;
    end
  end
  wire rst_n_i = rst_n_s2;

  // --- one-hot state register (§6.2): the flop output IS the state ---
  (* gp_src = "vacuous_mutex.yaml:14:states" *)
  reg state_A;
  (* gp_src = "vacuous_mutex.yaml:14:states" *)
  reg state_B;
  (* gp_src = "vacuous_mutex.yaml:17:transitions[0]" *)
  wire t_0 = (state_A & x);
  (* gp_src = "vacuous_mutex.yaml:18:transitions[1]" *)
  wire t_1 = (state_A & (~x));
  (* gp_src = "vacuous_mutex.yaml:19:transitions[2]" *)
  wire t_2 = (state_B & 1'b1);
  (* gp_src = "vacuous_mutex.yaml:14:states" *)
  wire next_A = t_1 | t_2;
  (* gp_src = "vacuous_mutex.yaml:14:states" *)
  wire next_B = t_0;
  (* gp_src = "vacuous_mutex.yaml:14:states" *)
  wire state_active = (state_A | state_B);
  (* gp_src = "vacuous_mutex.yaml:14:states" *)
  wire set_feedback = ~state_active;
  always @(posedge clk or negedge rst_n_i) begin
    if (!rst_n_i) begin
      state_A <= 1'b0;
      state_B <= 1'b0;
    end else begin
      state_A <= next_A | set_feedback;
      state_B <= next_B;
    end
  end

  (* gp_src = "vacuous_mutex.yaml:21:output_logic.a" *)
  wire a_int = state_B;
  assign a = a_int;
  (* gp_src = "vacuous_mutex.yaml:23:output_logic.b" *)
  wire b_int = 1'b0;
  assign b = b_int;

`ifdef GP_FORMAL
`include "properties.sv"
`endif
endmodule
