/**
 * The three views the fake core hid, driven against the REAL core.
 *
 * `docs/GUI-AUDIT.md` found the renderer wired to `mapped-netlist`,
 * `provenance` and `analyse` while the CLI registered none of them, so the
 * schematic's netlist, the linked-selection spine and the analysis dashboard
 * were all dead in the real app — and every test passed because every test
 * asked the fake. `contract-commands.spec.ts` now makes that class of defect
 * impossible; this spec makes it *visible*, by exercising the three views
 * against the real Python core.
 *
 * Like the GUI-audit regressions, these are hermetic: they seed the netlist
 * files a real `gatepack build` would have written (`mapped.json`, `packed.json`,
 * `premap.json`, `cells.lib`) so no Yosys is needed. There is deliberately no
 * `test.skip` here: if the real core is unavailable the launch helper throws and
 * the test FAILS — a skip is not a pass, for the same reason the `toolchain` CI
 * job greps its own log for "skipped".
 */

import { _electron, expect, test, type ElectronApplication, type Page } from '@playwright/test';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const APP_DIR = path.resolve(HERE, '..', '..');
const REPO_ROOT = path.resolve(APP_DIR, '..');
const FIXTURES = path.join(REPO_ROOT, 'tests', 'fixtures', 'provenance', 'xor2');

const DESIGN = `name: t
timing_model: synchronous
clock: {signal: clk, freq_hz: 1000, source: OSC}
reset: {signal: rst_n, active: low, source: SUPERVISOR}
encoding: one_hot
inputs:
  - {name: a, sync: false}
  - {name: b, sync: false}
outputs:
  - {name: y}
states: [S0]
initial: S0
transitions:
  - {from: S0, to: S0, when: "1"}
output_logic:
  y: "a & b"
`;

const MAPPED_JSON = JSON.stringify({
  creator: 'Yosys 0.23',
  modules: {
    t: {
      ports: {
        a: { direction: 'input', bits: [0] },
        b: { direction: 'input', bits: [1] },
        y: { direction: 'output', bits: [2] },
      },
      netnames: {
        a: { hide_name: 0, bits: [0] },
        b: { hide_name: 0, bits: [1] },
        y: { hide_name: 0, bits: [2] },
      },
      cells: {
        '$abc$148$99$154': {
          hide_name: 1,
          type: 'NAND2',
          parameters: {},
          attributes: {},
          connections: { A: [0], B: [1], Y: [2] },
        },
      },
    },
  },
});

const PACKED_JSON = JSON.stringify({
  packages: [
    {
      refdes: 'U1',
      partNumber: '74AUP1G00',
      cells: ['NAND2__5150c006'],
      instanceCells: ['$abc$148$99$154'],
      capacity: 1,
      spare: 0,
      rationale: 'function group: NAND2 (1G00) holds 1 gate(s)',
    },
  ],
});

const CELLS_LIB = `/* Generated by gatepack (C2). */
library (gatepack) {
  cell (NAND2) {
    area : 1.0;
    pin(A) { direction : input; capacitance : 0.0; }
    pin(B) { direction : input; capacitance : 0.0; }
    pin(Y) { direction : output; function : "(!(A & B))"; }
  }
  cell (DFF_R) {
    area : 1.0;
    ff (IQ, IQN) { next_state : "D"; clocked_on : "CK"; clear : "!RST_N"; }
    pin(D) { direction : input; capacitance : 0.0; }
    pin(CK) { direction : input; clock : true; }
    pin(RST_N) { direction : input; capacitance : 0.0; }
    pin(Q) { direction : output; function : "IQ"; }
  }
}
`;

let realCorePath: string | null = null;

function getRealCore(): string | null {
  const py = path.join(REPO_ROOT, '.venv', 'bin', 'python');
  if (!fs.existsSync(py)) return null;
  if (realCorePath === null) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gatepack-realcore-'));
    realCorePath = path.join(dir, 'gatepack');
    // PYTHONPATH is required: the core is spawned with cwd = the opened project
    // directory, so `python -m gatepack.cli` only resolves when PYTHONPATH points
    // at the repo root (the same thing `main/core.cts` does for `.venv/bin/python`).
    fs.writeFileSync(
      realCorePath,
      `#!/bin/sh\nexport PYTHONPATH="${REPO_ROOT}"\nexec "${py}" -m gatepack.cli "$@"\n`,
    );
    fs.chmodSync(realCorePath, 0o755);
  }
  return realCorePath;
}

interface Launched {
  app: ElectronApplication;
  page: Page;
}

async function launchRealCoreApp(): Promise<Launched> {
  const core = getRealCore();
  if (core === null) {
    // No skip: a missing real core is a failed test, never a quietly skipped one.
    throw new Error('real core not locatable (.venv/bin/python)');
  }
  const app = await _electron.launch({
    args: [APP_DIR],
    env: {
      ...process.env,
      GATEPACK_CORE: core,
      GATEPACK_SESSION_DIR: fs.mkdtempSync(path.join(os.tmpdir(), 'gatepack-session-')),
    },
  });
  const page = await app.firstWindow();
  await page.waitForFunction(() => typeof (window as any).gatepack !== 'undefined');
  return { app, page };
}

/** A project directory seeded with `design.yaml` plus the given `.gatepack/out` files. */
function makeProjectDir(outFiles: Record<string, string>, design = DESIGN): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gatepack-views-'));
  fs.writeFileSync(path.join(dir, 'design.yaml'), design);
  const out = path.join(dir, '.gatepack', 'out');
  fs.mkdirSync(out, { recursive: true });
  for (const [name, content] of Object.entries(outFiles)) {
    fs.writeFileSync(path.join(out, name), content);
  }
  return dir;
}

test.describe('real-core views', () => {
  let launched: Launched | null = null;

  test.afterEach(async () => {
    if (launched) {
      await launched.app.close();
      launched = null;
    }
  });

  test('the schematic renders the mapped netlist from the real core', async () => {
    launched = await launchRealCoreApp();
    const page = launched.page;

    const dir = makeProjectDir({ 'mapped.json': MAPPED_JSON, 'packed.json': PACKED_JSON });
    const opened = await page.evaluate(
      (p) => (window as any).gatepack.openProjectPath(p),
      dir,
    );
    expect(opened.ok).toBe(true);

    await page.getByTestId('nav-schematic').click();
    // The schematic draws an SVG from `gatepack mapped-netlist` + `packed-netlist`;
    // a dead command surfaces GP9002 as `schematic-error` instead.
    const svg = page.locator('[data-testid="schematic-svg"] svg');
    await expect(svg).toHaveCount(1, { timeout: 30_000 });
    await expect(page.locator('[data-testid="schematic-error"]')).toHaveCount(0);
  });

  test('the provenance spine returns real links from the real core', async () => {
    launched = await launchRealCoreApp();
    const page = launched.page;

    const outFiles = {
      'premap.json': fs.readFileSync(path.join(FIXTURES, 'premap.json'), 'utf8'),
      'mapped.json': fs.readFileSync(path.join(FIXTURES, 'mapped.json'), 'utf8'),
      'post_abc.json': fs.readFileSync(path.join(FIXTURES, 'post_abc.json'), 'utf8'),
    };
    const dir = makeProjectDir(outFiles);
    const opened = await page.evaluate(
      (p) => (window as any).gatepack.openProjectPath(p),
      dir,
    );
    expect(opened.ok).toBe(true);

    const env = await page.evaluate(() => (window as any).gatepack.provenance());
    expect(env.ok, JSON.stringify(env)).toBe(true);
    expect(env.data.coverage).toBeGreaterThan(0);

    // The spine's data contract: `output_logic.y` links exactly to the `y_int`
    // net (the combinational carrier), with a surviving attribute.
    const entries = env.data.entries as Array<{ pointer: string; nets: string[]; confidence: string }>;
    const outputLogic = entries.find((e) => e.pointer.endsWith('output_logic.y'));
    expect(outputLogic).toBeTruthy();
    expect(outputLogic!.confidence).toBe('exact');
    expect(outputLogic!.nets).toContain('y_int');
  });

  test('the analysis dashboard renders metrics from the real core', async () => {
    launched = await launchRealCoreApp();
    const page = launched.page;

    const dir = makeProjectDir({
      'mapped.json': MAPPED_JSON,
      'cells.lib': CELLS_LIB,
      'generated.v': 'module t;\nendmodule\n',
    });
    const opened = await page.evaluate(
      (p) => (window as any).gatepack.openProjectPath(p),
      dir,
    );
    expect(opened.ok).toBe(true);

    await page.getByTestId('nav-analysis').click();
    await page.getByRole('button', { name: 'Run analysis' }).click();

    // `analyse` succeeded and the dashboard shows the stuck-at classification,
    // not the `analysis-error` note that a dead command (GP9002) would produce.
    await expect(page.locator('[data-testid="fault-detected"]')).toBeVisible({ timeout: 30_000 });
    await expect(page.locator('[data-testid="analysis-error"]')).toHaveCount(0);
  });
});
