/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

module pelican(clk, rst_n, request, hold, traffic_red, traffic_amber, traffic_green, walk);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input clk;
  wire clk;
  input hold;
  wire hold;
  wire hold_i;
  wire hold_s1;
  wire hold_s2;
  wire next_CLEAR;
  wire next_CROSS;
  wire next_GO;
  wire next_WARN;
  input request;
  wire request;
  wire request_i;
  wire request_s1;
  wire request_s2;
  input rst_n;
  wire rst_n;
  wire rst_n_i;
  wire rst_n_s1;
  wire rst_n_s2;
  wire state_CLEAR;
  wire state_CROSS;
  wire state_GO;
  wire state_STOP;
  wire state_WARN;
  wire t_0;
  wire t_2;
  wire t_3;
  wire t_5;
  wire t_6;
  output traffic_amber;
  wire traffic_amber;
  wire traffic_amber_int;
  output traffic_green;
  wire traffic_green;
  wire traffic_green_int;
  output traffic_red;
  wire traffic_red;
  wire traffic_red_int;
  output walk;
  wire walk;
  wire walk_int;
  INV _08_ (
    .A(hold_s2),
    .Y(_01_)
  );
  NAND2 _09_ (
    .A(request_s2),
    .B(_01_),
    .Y(_02_)
  );
  AND3 _10_ (
    .A(request_s2),
    .B(_01_),
    .C(state_GO),
    .Y(next_WARN)
  );
  AND2 _11_ (
    .A(_01_),
    .B(state_STOP),
    .Y(next_CROSS)
  );
  AND2 _12_ (
    .A(state_GO),
    .B(_02_),
    .Y(_03_)
  );
  OR2 _13_ (
    .A(state_CLEAR),
    .B(_03_),
    .Y(next_GO)
  );
  OR2 _14_ (
    .A(state_STOP),
    .B(state_CLEAR),
    .Y(_04_)
  );
  OR2 _15_ (
    .A(state_CROSS),
    .B(_04_),
    .Y(traffic_red)
  );
  NOR3 _16_ (
    .A(state_GO),
    .B(state_CROSS),
    .C(_04_),
    .Y(_05_)
  );
  AND2 _17_ (
    .A(hold_s2),
    .B(state_STOP),
    .Y(_06_)
  );
  OR2 _18_ (
    .A(state_WARN),
    .B(_06_),
    .Y(_07_)
  );
  OR2 _19_ (
    .A(_05_),
    .B(_07_),
    .Y(_00_)
  );
  DFF_R _20_ (
    .CK(clk),
    .D(next_GO),
    .Q(state_GO),
    .RST_N(rst_n_s2)
  );
  DFF_R _21_ (
    .CK(clk),
    .D(next_WARN),
    .Q(state_WARN),
    .RST_N(rst_n_s2)
  );
  DFF_R _22_ (
    .CK(clk),
    .D(_00_),
    .Q(state_STOP),
    .RST_N(rst_n_s2)
  );
  DFF_R _23_ (
    .CK(clk),
    .D(next_CROSS),
    .Q(state_CROSS),
    .RST_N(rst_n_s2)
  );
  DFF_R _24_ (
    .CK(clk),
    .D(state_CROSS),
    .Q(state_CLEAR),
    .RST_N(rst_n_s2)
  );
  DFF_R _25_ (
    .CK(clk),
    .D(1'h1),
    .Q(rst_n_s1),
    .RST_N(rst_n)
  );
  DFF_R _26_ (
    .CK(clk),
    .D(rst_n_s1),
    .Q(rst_n_s2),
    .RST_N(rst_n)
  );
  DFF_R _27_ (
    .CK(clk),
    .D(hold),
    .Q(hold_s1),
    .RST_N(rst_n)
  );
  DFF_R _28_ (
    .CK(clk),
    .D(hold_s1),
    .Q(hold_s2),
    .RST_N(rst_n)
  );
  DFF_R _29_ (
    .CK(clk),
    .D(request),
    .Q(request_s1),
    .RST_N(rst_n)
  );
  DFF_R _30_ (
    .CK(clk),
    .D(request_s1),
    .Q(request_s2),
    .RST_N(rst_n)
  );
  assign hold_i = hold_s2;
  assign next_CLEAR = state_CROSS;
  assign request_i = request_s2;
  assign rst_n_i = rst_n_s2;
  assign t_0 = next_WARN;
  assign t_2 = state_WARN;
  assign t_3 = next_CROSS;
  assign t_5 = state_CROSS;
  assign t_6 = state_CLEAR;
  assign traffic_amber = state_WARN;
  assign traffic_amber_int = state_WARN;
  assign traffic_green = state_GO;
  assign traffic_green_int = state_GO;
  assign traffic_red_int = traffic_red;
  assign walk = state_CROSS;
  assign walk_int = state_CROSS;
endmodule
