/**
 * gatepack IPC contract — the single seam between the Electron main process,
 * the renderer, and the Python core.
 *
 * This file is authored by hand and is AUTHORITATIVE. Three pieces of work
 * depend on it and must not change it unilaterally:
 *
 *   - the core (`gatepack/cli.py --json`) must EMIT exactly these envelopes;
 *   - the main process (C9) must VALIDATE them before they cross IPC;
 *   - the renderer must CONSUME them and nothing else.
 *
 * If you believe a field is missing, record it in docs/BUILD-NOTES.md and work
 * around it. Do not edit this file. A silent divergence here is the one bug
 * that costs all three work packages at once.
 *
 * Design references: §5.2 (security posture), §16 (C9–C15), §16.1 (budget).
 */

/* ------------------------------------------------------------------ */
/* Envelope                                                            */
/* ------------------------------------------------------------------ */

/**
 * Every `gatepack <cmd> --json` invocation prints exactly one of these to
 * stdout, and nothing else. Diagnostics go to stderr. Exit code is 0 for
 * `ok: true` and non-zero otherwise; the renderer must key on `ok`, never on
 * the exit code alone.
 */
export type Envelope<T> =
  | { ok: true; command: string; schema: 1; data: T; warnings: Diagnostic[] }
  | { ok: false; command: string; schema: 1; error: Diagnostic; warnings: Diagnostic[] };

/**
 * A diagnostic anchored, where possible, to a location in the source
 * specification. `path` is relative to the project root. `pointer` is the
 * §15.1 provenance token (`design.yaml:12:transitions[3]`) when one exists —
 * it is what makes a diagnostic selectable into the FSM graph (§15.2).
 */
export interface Diagnostic {
  severity: 'error' | 'warning' | 'info';
  /** Stable machine-readable code, e.g. `GP1003`. Never localise this. */
  code: string;
  message: string;
  path?: string;
  line?: number;
  column?: number;
  pointer?: string;
}

/* ------------------------------------------------------------------ */
/* Per-command payloads                                                */
/* ------------------------------------------------------------------ */

/** `gatepack compile --json` */
export interface CompileResult {
  verilogPath: string;
  propertiesPath: string | null;
  flopCount: number;
  stateCount: number;
  encoding: 'one_hot' | 'binary' | 'gray' | 'johnson';
  /** §9.4 suggestion surfaced by the front-end, or null. */
  johnsonSuggestion: string | null;
}

/** `gatepack estimate --json` — the §6 viability verdict. */
export interface EstimateResult {
  verdict: 'green' | 'amber' | 'red';
  reasons: string[];
  packageCount: number;
  flopCount: number;
  cellCounts: Record<string, number>;
  /** Populated when the verdict is red (§6, §24.1 CPLD escape hatch). */
  alternative: string | null;
}

/**
 * `gatepack verify --json`.
 *
 * §C15 [R4-25]: FOUR states, not three. `bounded` exists because k-induction
 * does not always close and BMC is the fallback (§21.5). Rendering a bounded
 * result as a plain pass would recreate the vacuous-pass failure mode that R2
 * and R18 exist to prevent, so `bound` is REQUIRED when status is `bounded`.
 */
export type CheckStatus = 'passed' | 'bounded' | 'failed' | 'not_run';

export interface Check {
  name: string;
  kind: 'equivalence' | 'simulation' | 'mutation' | 'property' | 'hazard';
  status: CheckStatus;
  /** Induction/BMC depth. Required iff status === 'bounded'. */
  bound?: number;
  /** Why a check did not run — a missing tool is a legitimate, visible state. */
  skippedReason?: string;
  durationMs: number;
  counterexample?: Counterexample;
}

/** A failing trace, selectable into the FSM graph and schematic (§15.2). */
export interface Counterexample {
  /** One entry per cycle; each maps signal name -> '0' | '1' | 'x'. */
  steps: Array<Record<string, string>>;
  /** Provenance pointers for the spec constructs implicated in the trace. */
  pointers: string[];
}

export interface VerifyResult {
  checks: Check[];
  /** True iff every check is `passed`. A `bounded` check does NOT satisfy this. */
  allPassed: boolean;
}

/** `gatepack build --json` */
export interface BuildResult {
  bomPath: string;
  netlistPath: string;
  reportPath: string;
  mappedJsonPath: string;
  packageCount: number;
  spareCount: number;
  packCost: number;
  bom: BomLine[];
  analysis: AnalysisSummary;
  /**
   * Mapped-netlist instance name -> stable cell name.
   *
   * A packing override (`packing.force_groups` in `design.yaml`) is resolved
   * against the **stable** names. The names the renderer sees from
   * `mappedNetlist()` are ABC's instance names (`$abc$148$...$154`), which are
   * renumbered by every synthesis — persisting one is refused by the packer
   * today, and would silently point at a different gate tomorrow if it were
   * not. Translate through this map before writing an override.
   */
  stableCellNames: Record<string, string>;
}

export interface BomLine {
  partNumber: string;
  manufacturers: string[];
  package: string;
  quantity: number;
  refdes: string[];
  tier: string;
  /** §C13: a single-sourced part gets a hard visual marker. */
  singleSourced: boolean;
  /**
   * Gates this package holds.
   *
   * The packing view needs it to know whether grouping can achieve anything:
   * with a one-gate-per-package library, `packed === unpacked` by construction
   * and a spare gate cannot exist. Derive that from this field — never
   * hardcode it, because the library gained multi-gate parts once already and
   * a hardcoded "grouping is inert" note became a false statement about the
   * user's own design.
   */
  gatesPerPackage: number;
}

/** §C14 dashboard metrics, each against its §10.2 constraint. */
export interface AnalysisSummary {
  metrics: Metric[];
  /** §13.1 SCOAP delta table. */
  scoap: Array<{ net: string; controllability0: number; controllability1: number; observability: number }>;
  /** §13.2 single stuck-at classification counts. */
  faults: Record<'detected' | 'undetected' | 'redundant' | 'untestable', number>;
  /** §24.1: constructs that would block a CPLD fallback. Empty is the good case. */
  cpldBlockers: Diagnostic[];
}

export interface Metric {
  name: string;
  value: number;
  unit: string;
  /** The §10.2 constraint bound, or null if unconstrained. */
  limit: number | null;
  /** True when a limit exists and is exceeded — renders red (§C14). */
  violated: boolean;
}

/** `gatepack analyse --json` returns AnalysisSummary directly. */

/* ------------------------------------------------------------------ */
/* Exhaustive simulation (§C11)                                        */
/* ------------------------------------------------------------------ */

/**
 * One row of the exhaustive check C4 already performs: the specified output
 * values against the values the mapped netlist actually produces.
 *
 * C11's divergence column is the most valuable thing in the truth table view,
 * and it must come from the core. Computing "simulated" outputs in the
 * renderer would compare the specification against itself and could never
 * disagree — a check incapable of failing, which is the failure mode this
 * project exists to prevent.
 */
export interface SimulationRow {
  /** Input assignment, signal name -> '0' | '1'. */
  inputs: Record<string, string>;
  /** For a sequential design, the state this row was evaluated in. */
  state?: string;
  /** What the specification says the outputs should be. */
  expected: Record<string, string>;
  /** What the mapped netlist produces. Absent when synthesis has not run. */
  actual?: Record<string, string>;
  /** True when expected and actual disagree on any output. */
  diverges: boolean;
}

export interface SimulationTable {
  inputNames: string[];
  outputNames: string[];
  rows: SimulationRow[];
  /** Minterms the specification leaves as don't-care. */
  dontCareCount: number;
  /** States/minterms proven unreachable, so never simulated. */
  unreachableCount: number;
  /** False when the input space was too large to enumerate exhaustively. */
  exhaustive: boolean;
}

/* ------------------------------------------------------------------ */
/* Provenance (§15)                                                    */
/* ------------------------------------------------------------------ */

/**
 * The §15.1 provenance spine, emitted alongside a build. This is what makes
 * linked selection possible; M0 measured that the carrier is the NET
 * attribute, not the cell attribute, because `abc` destroys cell attributes
 * and preserves net attributes (docs/M0-FINDINGS.md §3).
 */
export interface ProvenanceMap {
  /** pointer -> the nets and cells it produced. Partial links are explicit. */
  entries: Array<{
    pointer: string;
    nets: string[];
    cells: string[];
    /** `exact` from a surviving attribute; `inferred` from structural match. */
    confidence: 'exact' | 'inferred';
  }>;
  /** Fraction of spec constructs with at least one link, 0..1. Reported always. */
  coverage: number;
}

/* ------------------------------------------------------------------ */
/* The bridge exposed to the renderer                                  */
/* ------------------------------------------------------------------ */

/**
 * §5.2: the renderer NEVER touches `fs`, `child_process`, or arbitrary paths.
 * Everything it may do is on this interface, exposed via `contextBridge` as
 * `window.gatepack`. Every argument is schema-validated in the main process
 * before use; treat the renderer as untrusted.
 *
 * All long-running calls accept an AbortSignal-like token: §16.1 requires that
 * in-flight work is cancelled on new input, because a stale result arriving
 * after a newer edit is a correctness bug, not a performance issue.
 */
export interface GatepackApi {
  /* --- session (C9) --- */
  openProject(): Promise<Envelope<ProjectInfo>>;
  /** Accepts a directory or a single `.gpk` file (§10.4). */
  openProjectPath(path: string): Promise<Envelope<ProjectInfo>>;
  closeProject(): Promise<void>;
  saveProject(): Promise<Envelope<ProjectInfo>>;
  /** Re-bundles the working form back into a single `.gpk` (§10.4). */
  saveProjectAs(gpkPath: string): Promise<Envelope<ProjectInfo>>;

  readSpec(): Promise<Envelope<{ text: string; path: string }>>;
  writeSpec(text: string): Promise<Envelope<{ path: string }>>;

  /* --- core invocations --- */
  compile(token?: string): Promise<Envelope<CompileResult>>;
  estimate(token?: string): Promise<Envelope<EstimateResult>>;
  verify(token?: string): Promise<Envelope<VerifyResult>>;
  build(token?: string): Promise<Envelope<BuildResult>>;
  analyse(token?: string): Promise<Envelope<AnalysisSummary>>;
  provenance(): Promise<Envelope<ProvenanceMap>>;
  /** §C11 divergence data — the exhaustive check, rendered interactively. */
  simulate(token?: string): Promise<Envelope<SimulationTable>>;
  /** Yosys `write_json` output for C12/netlistsvg. */
  mappedNetlist(): Promise<Envelope<unknown>>;
  /** Cancel an in-flight call started with this token (§16.1). */
  cancel(token: string): Promise<void>;

  /* --- events, main -> renderer --- */
  onProjectChanged(cb: (info: ProjectInfo) => void): () => void;
  /** Fired when a watched file changes on disk; debounced in main (C9). */
  onFileChanged(cb: (paths: string[]) => void): () => void;
  onProgress(cb: (p: { token: string; stage: string; percent?: number }) => void): () => void;
}

export interface ProjectInfo {
  /** Directory root, or the `.gpk` path when opened in single-file form. */
  path: string;
  form: 'directory' | 'gpk';
  designPath: string;
  libraryPath: string | null;
  dirty: boolean;
  /** null when the project is not in a git working tree. */
  git: { branch: string; dirtyFiles: string[] } | null;
}

declare global {
  interface Window {
    gatepack: GatepackApi;
  }
}
