// Generated by gatepack (C1). Do not edit.
`timescale 1ns/1ps

(* gp_src = "property_violating.yaml:1:name" *)
module property_violating (
  input wire clk,
  input wire rst_n,
  input wire x,
  output wire enable,
  output wire fault
);


  // reset: async assert, sync de-assert (§9.3)
  (* gp_src = "property_violating.yaml:4:reset" *)
  reg rst_n_s1;
  (* gp_src = "property_violating.yaml:4:reset" *)
  reg rst_n_s2;
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rst_n_s1 <= 1'b0;
      rst_n_s2 <= 1'b0;
    end else begin
      rst_n_s1 <= 1'b1;
      rst_n_s2 <= rst_n_s1;
    end
  end
  wire rst_n_i = rst_n_s2;

  // --- one-hot state register (§6.2): the flop output IS the state ---
  (* gp_src = "property_violating.yaml:10:states" *)
  reg state_A;
  (* gp_src = "property_violating.yaml:10:states" *)
  reg state_B;
  (* gp_src = "property_violating.yaml:13:transitions[0]" *)
  wire t_0 = (state_A & x);
  (* gp_src = "property_violating.yaml:14:transitions[1]" *)
  wire t_1 = (state_A & (~x));
  (* gp_src = "property_violating.yaml:15:transitions[2]" *)
  wire t_2 = (state_B & (~x));
  (* gp_src = "property_violating.yaml:16:transitions[3]" *)
  wire t_3 = (state_B & x);
  (* gp_src = "property_violating.yaml:10:states" *)
  wire next_A = t_1 | t_2;
  (* gp_src = "property_violating.yaml:10:states" *)
  wire next_B = t_0 | t_3;
  (* gp_src = "property_violating.yaml:10:states" *)
  wire state_active = (state_A | state_B);
  (* gp_src = "property_violating.yaml:10:states" *)
  wire set_feedback = ~state_active;
  always @(posedge clk or negedge rst_n_i) begin
    if (!rst_n_i) begin
      state_A <= 1'b0;
      state_B <= 1'b0;
    end else begin
      state_A <= next_A | set_feedback;
      state_B <= next_B;
    end
  end

  (* gp_src = "property_violating.yaml:18:output_logic.enable" *)
  wire enable_int = state_B;
  assign enable = enable_int;
  (* gp_src = "property_violating.yaml:19:output_logic.fault" *)
  wire fault_int = state_B;
  assign fault = fault_int;

`ifdef GP_FORMAL
`include "properties.sv"
`endif
endmodule
