// Generated by gatepack (C2) — behavioural models for Icarus (§C4.3).
// Do not edit. The M-cell models are appended from gatepack/macros/.
`timescale 1ns/1ps

module INV (
  input wire A,
  output wire Y
);
  assign Y = (~A);
endmodule

module BUF (
  input wire A,
  output wire Y
);
  assign Y = A;
endmodule

module NAND2 (
  input wire A,
  input wire B,
  output wire Y
);
  assign Y = (~(A & B));
endmodule

module NAND3 (
  input wire A,
  input wire B,
  input wire C,
  output wire Y
);
  assign Y = (~((A & B) & C));
endmodule

module NOR2 (
  input wire A,
  input wire B,
  output wire Y
);
  assign Y = (~(A | B));
endmodule

module NOR3 (
  input wire A,
  input wire B,
  input wire C,
  output wire Y
);
  assign Y = (~((A | B) | C));
endmodule

module AND2 (
  input wire A,
  input wire B,
  output wire Y
);
  assign Y = (A & B);
endmodule

module AND3 (
  input wire A,
  input wire B,
  input wire C,
  output wire Y
);
  assign Y = ((A & B) & C);
endmodule

module OR2 (
  input wire A,
  input wire B,
  output wire Y
);
  assign Y = (A | B);
endmodule

module XOR2 (
  input wire A,
  input wire B,
  output wire Y
);
  assign Y = (A ^ B);
endmodule

module DFF (
  input wire D,
  input wire CK,
  output reg Q
);
  always @(posedge CK) begin
    Q <= D;
  end
endmodule

module DFF_R (
  input wire D,
  input wire CK,
  input wire RST_N,
  output reg Q
);
  always @(posedge CK or negedge RST_N) begin
    if (!RST_N) Q <= 1'b0;
    else Q <= D;
  end
endmodule

module DFF_SR (
  input wire D,
  input wire CK,
  input wire SET_N,
  input wire RST_N,
  output reg Q
);
  always @(posedge CK or negedge RST_N or negedge SET_N) begin
    if (!RST_N) Q <= 1'b0;
    else if (!SET_N) Q <= 1'b1;
    else Q <= D;
  end
endmodule

module INV (
  input wire A,
  output wire Y
);
  assign Y = (~A);
endmodule

module INV (
  input wire A,
  output wire Y
);
  assign Y = (~A);
endmodule

module NAND2 (
  input wire A,
  input wire B,
  output wire Y
);
  assign Y = (~(A & B));
endmodule

module NOR2 (
  input wire A,
  input wire B,
  output wire Y
);
  assign Y = (~(A | B));
endmodule

module AND2 (
  input wire A,
  input wire B,
  output wire Y
);
  assign Y = (A & B);
endmodule

module OR2 (
  input wire A,
  input wire B,
  output wire Y
);
  assign Y = (A | B);
endmodule

// CNT4 — 4-bit synchronous binary counter (§9.4).
//
// Hand-written behavioural model.  M-cells are instantiated explicitly by the
// front-end and are NEVER inferred by Yosys (§8, §9.4).  This file is the
// single model used by both exhaustive simulation (appended to cells_sim.v)
// and C4 equivalence checking — the two MUST be the same file (§19 R25).
//
// Physical binding: 74LVC161 (see gatepack/macros/bindings.py).
// Candidate part — unverified, per §9 (datasheet confirmation pending).

`timescale 1ns/1ps

module CNT4 (
  input  wire      CLK,
  input  wire      RST_N,   // asynchronous reset, active low
  input  wire      EN,      // count enable, active high
  output reg [3:0] Q
);
  always @(posedge CLK or negedge RST_N) begin
    if (!RST_N)
      Q <= 4'd0;
    else if (EN)
      Q <= Q + 1'b1;
  end
endmodule
