"""Behavioural Verilog + properties emission (C1, §12 C1, §15.1).

Every construct carries a ``(* src = "design.yaml:<line>:<path>" *)`` attribute —
the provenance spine of §15.1.  Attributes are load-bearing, not decoration: C3
captures them from ``premap.json`` before ``dfflibmap``/``abc`` strip them
([R4-14]).

Encoding:

* ``one_hot`` (default) — one register bit per state named ``state_<NAME>``; the
  next-state term for each transition is a named wire ``t_<index>`` carrying the
  transition's own ``src`` attribute, so provenance survives into the netlist.
* ``binary`` / ``gray`` — a ``state`` vector with ``STATE_<NAME>`` localparams and
  a ``case`` next-state block.
"""

from __future__ import annotations

from gatepack.frontend import expr as expr_mod
from gatepack.frontend.model import CompiledDesign
from gatepack.frontend.schema import Reset


def _attr(compiled: CompiledDesign, path: str) -> str:
    line = compiled.provenance.get(path)
    display = str(line) if line is not None else "?"
    return f'(* src = "{compiled.source_name}:{display}:{path}" *)'


def _reset_active_low(reset: Reset) -> bool:
    return reset.active == "low"


def emit_verilog(compiled: CompiledDesign) -> str:
    lines: list[str] = []
    design = compiled.design
    reset = design.reset
    active_low = _reset_active_low(reset)

    clock_name = design.clock.signal if design.clock else "clk"
    reset_name = reset.signal
    reset_i = f"{reset_name}_i"

    # --- ports -----------------------------------------------------------------
    lines.append("// Generated by gatepack (C1). Do not edit.")
    lines.append("`timescale 1ns/1ps")
    lines.append("")
    lines.append(_attr(compiled, "name"))
    lines.append(f"module {design.name} (")
    ports = [f"input wire {clock_name}", f"input wire {reset_name}"]
    ports += [f"input wire {name}" for name in compiled.input_names]
    ports += [f"output wire {name}" for name in compiled.output_names]
    lines.append(",\n".join(f"  {p}" for p in ports))
    lines.append(");")
    lines.append("")

    # --- input synchronisers ---------------------------------------------------
    var_map: dict[str, str] = {}
    for name in compiled.input_names:
        if compiled.input_sync[name]:
            path = f"inputs[{compiled.input_names.index(name)}]"
            lines.append(f"  // two-stage synchroniser for input {name} (§9.3)")
            lines.append(f"  {_attr(compiled, path)}")
            lines.append(f"  reg {name}_s1;")
            lines.append(f"  {_attr(compiled, path)}")
            lines.append(f"  reg {name}_s2;")
            sync_edge = f"negedge {reset_name}" if active_low else f"posedge {reset_name}"
            sync_assert = f"!{reset_name}" if active_low else reset_name
            lines.append(f"  always @(posedge {clock_name} or {sync_edge}) begin")
            lines.append(f"    if ({sync_assert}) begin")
            lines.append(f"      {name}_s1 <= 1'b0;")
            lines.append(f"      {name}_s2 <= 1'b0;")
            lines.append("    end else begin")
            lines.append(f"      {name}_s1 <= {name};")
            lines.append(f"      {name}_s2 <= {name}_s1;")
            lines.append("    end")
            lines.append("  end")
            lines.append(f"  wire {name}_i = {name}_s2;")
            var_map[name] = f"{name}_i"
        else:
            var_map[name] = name
    if compiled.input_names:
        lines.append("")

    # --- reset de-assert synchroniser -----------------------------------------
    if reset.sync_deassert:
        lines.append("  // reset: async assert, sync de-assert (§9.3)")
        lines.append(f"  {_attr(compiled, 'reset')}")
        lines.append(f"  reg {reset_name}_s1;")
        lines.append(f"  {_attr(compiled, 'reset')}")
        lines.append(f"  reg {reset_name}_s2;")
        if active_low:
            lines.append(f"  always @(posedge {clock_name} or negedge {reset_name}) begin")
            lines.append(f"    if (!{reset_name}) begin")
            lines.append(f"      {reset_name}_s1 <= 1'b0;")
            lines.append(f"      {reset_name}_s2 <= 1'b0;")
            lines.append("    end else begin")
            lines.append(f"      {reset_name}_s1 <= 1'b1;")
            lines.append(f"      {reset_name}_s2 <= {reset_name}_s1;")
            lines.append("    end")
            lines.append("  end")
        else:
            lines.append(f"  always @(posedge {clock_name} or posedge {reset_name}) begin")
            lines.append(f"    if ({reset_name}) begin")
            lines.append(f"      {reset_name}_s1 <= 1'b1;")
            lines.append(f"      {reset_name}_s2 <= 1'b1;")
            lines.append("    end else begin")
            lines.append(f"      {reset_name}_s1 <= 1'b0;")
            lines.append(f"      {reset_name}_s2 <= {reset_name}_s1;")
            lines.append("    end")
            lines.append("  end")
        lines.append(f"  wire {reset_i} = {reset_name}_s2;")
        lines.append("")
    else:
        reset_i = reset_name

    # --- named expressions -----------------------------------------------------
    for name in compiled.design.expressions:
        ast = compiled.expression_asts[name]
        lines.append(f"  {_attr(compiled, f'expressions.{name}')}")
        lines.append(
            f"  wire {name} = {expr_mod.to_verilog(ast, var_map, _state_map(compiled))};"
        )
    if compiled.design.expressions:
        lines.append("")

    var_map.update({name: name for name in compiled.design.expressions})

    # --- state register --------------------------------------------------------
    if compiled.encoding == "one_hot":
        lines.extend(_emit_one_hot_state(compiled, clock_name, reset_i, active_low, var_map))
    else:
        lines.extend(_emit_encoded_state(compiled, clock_name, reset_i, active_low, var_map))

    # --- output logic ----------------------------------------------------------
    state_map = _state_map(compiled)
    for name in compiled.output_names:
        ast = compiled.output_asts[name]
        lines.append(f"  {_attr(compiled, f'output_logic.{name}')}")
        lines.append(
            f"  assign {name} = {expr_mod.to_verilog(ast, var_map, state_map)};"
        )

    # --- macros (behavioural models are an M8 deliverable) ---------------------
    for macro in compiled.design.macros:
        path = f"macros[{compiled.design.macros.index(macro)}]"
        enable = f", enable {macro.enable!r}" if macro.enable else ""
        lines.append(
            f"  {_attr(compiled, path)}"
        )
        lines.append(
            f"  // M-cell {macro.instance}: {macro.cell} (clock {macro.clock}{enable}); "
            f"behavioural model emitted at M8 (gatepack/macros/cells_sim.v)."
        )

    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)


def _emit_one_hot_state(
    compiled: CompiledDesign,
    clock_name: str,
    reset_i: str,
    active_low: bool,
    var_map: dict[str, str],
) -> list[str]:
    lines: list[str] = []
    design = compiled.design
    lines.append("  // --- one-hot state register (§6.2): the flop output IS the state ---")

    for state in compiled.state_order:
        lines.append(f"  {_attr(compiled, 'states')}")
        lines.append(f"  reg state_{state};")

    # per-transition terms
    for index, tr in enumerate(design.transitions):
        guard = expr_mod.to_verilog(compiled.transition_guards[index], var_map, {})
        lines.append(f"  {_attr(compiled, f'transitions[{index}]')}")
        lines.append(f"  wire t_{index} = (state_{tr.from_} & {guard});")

    # next-state per target
    transitions = design.transitions
    for target in compiled.state_order:
        terms = [
            f"t_{i}"
            for i, tr in enumerate(transitions)
            if tr.to == target
        ]
        expr = " | ".join(terms) if terms else "1'b0"
        lines.append(f"  {_attr(compiled, 'states')}")
        lines.append(f"  wire next_{target} = {expr};")

    edge = f"negedge {reset_i}" if active_low else f"posedge {reset_i}"
    assert_expr = f"!{reset_i}" if active_low else reset_i
    lines.append(f"  always @(posedge {clock_name} or {edge}) begin")
    lines.append(f"    if ({assert_expr}) begin")
    for state in compiled.state_order:
        value = "1'b1" if state == design.initial else "1'b0"
        lines.append(f"      state_{state} <= {value};")
    lines.append("    end else begin")
    for state in compiled.state_order:
        lines.append(f"      state_{state} <= next_{state};")
    lines.append("    end")
    lines.append("  end")
    lines.append("")
    return lines


def _emit_encoded_state(
    compiled: CompiledDesign,
    clock_name: str,
    reset_i: str,
    active_low: bool,
    var_map: dict[str, str],
) -> list[str]:
    lines: list[str] = []
    design = compiled.design
    width = compiled.state_width
    lines.append(f"  // --- {compiled.encoding}-encoded state register ---")

    for state in compiled.state_order:
        code = compiled.state_codes[state]
        lines.append(f"  localparam [{width - 1}:0] STATE_{state} = {width}'d{code};")

    lines.append(f"  reg [{width - 1}:0] state;")

    edge = f"negedge {reset_i}" if active_low else f"posedge {reset_i}"
    assert_expr = f"!{reset_i}" if active_low else reset_i
    init_code = compiled.state_codes[design.initial]
    lines.append(f"  always @(posedge {clock_name} or {edge}) begin")
    lines.append(f"    if ({assert_expr}) begin")
    lines.append(f"      state <= STATE_{design.initial};")
    lines.append("    end else begin")
    lines.append("      case (state)")

    grouped: dict[str, list[int]] = {}
    for index, tr in enumerate(design.transitions):
        grouped.setdefault(tr.from_, []).append(index)

    for state in compiled.state_order:
        indices = grouped.get(state, [])
        lines.append(f"        STATE_{state}: begin")
        if not indices:
            lines.append(f"          state <= state;")
        else:
            for pos, index in enumerate(indices):
                tr = design.transitions[index]
                guard = expr_mod.to_verilog(compiled.transition_guards[index], var_map, {})
                kw = "if" if pos == 0 else "else if"
                lines.append(
                    f"          {kw} ({guard}) state <= STATE_{tr.to};  "
                    f"// transitions[{index}]"
                )
            lines.append(f"          else state <= state;")
        lines.append("        end")
    lines.append("        default: state <= STATE_" + design.initial + ";")
    lines.append("      endcase")
    lines.append("    end")
    lines.append("  end")
    lines.append("")
    return lines


def _state_map(compiled: CompiledDesign) -> dict[str, str]:
    if compiled.encoding == "one_hot":
        return {s: f"state_{s}" for s in compiled.state_order}
    return {s: f"(state == STATE_{s})" for s in compiled.state_order}


def emit_properties(compiled: CompiledDesign) -> str:
    """Emit ``properties.sv`` (§11) — compiled at M2, discharged by sby at M6."""
    design = compiled.design
    reset = design.reset
    active_low = _reset_active_low(reset)
    clock_name = design.clock.signal if design.clock else "clk"
    reset_name = reset.signal
    lines: list[str] = []
    lines.append("// Generated by gatepack (C1). Discharged by sby (M6).")
    lines.append("`timescale 1ns/1ps")
    lines.append("")
    lines.append(f"module {design.name}_properties;")
    lines.append(f"  reg {clock_name} = 1'b0;")
    lines.append(f"  reg {reset_name} = 1'b0;")

    for name in compiled.input_names:
        lines.append(f"  reg {name} = 1'b0;")
    for name in compiled.output_names:
        lines.append(f"  wire {name};")

    conn = [f".{clock_name}({clock_name})", f".{reset_name}({reset_name})"]
    conn += [f".{name}({name})" for name in compiled.input_names]
    conn += [f".{name}({name})" for name in compiled.output_names]
    lines.append("")
    lines.append(f"  {design.name} dut ({', '.join(conn)});")
    lines.append("")
    lines.append(f"  always #1 {clock_name} = ~{clock_name};")
    lines.append("")
    lines.append("  initial begin")
    if active_low:
        lines.append(f"    {reset_name} = 1'b0;")
        lines.append(f"    #5 {reset_name} = 1'b1;")
    else:
        lines.append(f"    {reset_name} = 1'b1;")
        lines.append(f"    #5 {reset_name} = 1'b0;")
    lines.append("  end")
    lines.append("")

    disable = f"!{reset_name}" if active_low else reset_name

    for prop in design.properties:
        lines.append(f"  // {prop.kind}: {prop.name}")
        if prop.kind == "invariant":
            body = _property_body(compiled, prop.expr or "1")
            lines.append(f"  cover property (@(posedge {clock_name}) {body});")
            lines.append(
                f"  assert property (@(posedge {clock_name}) disable iff ({disable}) {body});"
            )
        elif prop.kind == "mutex":
            body = _property_body(compiled, prop.expr or "1")
            lines.append(f"  cover property (@(posedge {clock_name}) {body});")
            lines.append(
                f"  assert property (@(posedge {clock_name}) disable iff ({disable}) {body});"
            )
        elif prop.kind == "reachability":
            target = _property_body(compiled, _state_eq(prop.to or ""))
            lines.append(
                f"  // cover (BMC target): can {prop.to} be reached from {prop.from_}? "
                f"(from-state assumption: {prop.from_})"
            )
            lines.append(f"  cover property (@(posedge {clock_name}) {target});")
        else:  # liveness
            lines.append(
                f"  // liveness '{prop.expr}' is bounded; the bound is chosen at M6 "
                f"(§21.5). Not emitted as unbounded SVA."
            )
        lines.append("")

    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)


def _property_body(compiled: CompiledDesign, text: str) -> str:
    try:
        ast = expr_mod.parse(text)
    except expr_mod.ExprError:
        return text
    var_map = {name: f"dut.{name}" for name in compiled.input_names}
    var_map.update({name: f"dut.{name}" for name in compiled.design.expressions})
    var_map.update({name: f"dut.{name}" for name in compiled.output_names})
    state_map = {
        s: (f"dut.state_{s}" if compiled.encoding == "one_hot" else f"(dut.state == dut.STATE_{s})")
        for s in compiled.state_order
    }
    return expr_mod.to_verilog(ast, var_map, state_map)


def _state_eq(state: str) -> str:
    return f"state == {state}" if state else "1"
