"""Behavioural Verilog + properties emission (C1, §12 C1, §15.1).

Every construct carries a ``(* gp_src = "design.yaml:<line>:<path>" *)`` attribute
— the provenance spine of §15.1.  The attribute is deliberately **not** called
``src``: Yosys populates ``src`` itself with the Verilog file/line that created
each cell and its value wins over an emitted one (M0-FINDINGS §2).

Provenance rides on **named nets**, never on cells and never on a continuous
``assign`` (M0-FINDINGS §1, §3).  Every attribute is attached to the ``wire`` or
``reg`` *declaration* of the net it describes; where a construct has no
declaration of its own (the output logic), C1 emits an explicitly declared
intermediate wire so the provenance is not dropped.  Net attributes survive
``abc`` intact, which is what makes the §15.1 spine work at all for
combinational logic.

Encoding:

* ``one_hot`` (default) — one register bit per state named ``state_<NAME>``; the
  next-state term for each transition is a named wire ``t_<index>`` carrying the
  transition's own ``gp_src`` attribute, so provenance survives into the netlist.
  The initial state is realised as **set-via-feedback** on a reset-to-0 flop
  (M0-FINDINGS §6): every state flop resets to 0, and the all-zero condition
  feeds back to set the initial state, so no set-capable flop (``DFF_S``) is
  required.
* ``binary`` / ``gray`` — a ``state`` vector with ``STATE_<NAME>`` localparams and
  a ``case`` next-state block.
"""

from __future__ import annotations

from dataclasses import dataclass

from gatepack.frontend import expr as expr_mod
from gatepack.frontend.errors import CompileError
from gatepack.frontend.model import CompiledDesign
from gatepack.frontend.schema import Reset
from gatepack.macros import blackbox_module, get_spec


def _attr(compiled: CompiledDesign, path: str) -> str:
    line = compiled.provenance.get(path)
    display = str(line) if line is not None else "?"
    return f'(* gp_src = "{compiled.source_name}:{display}:{path}" *)'


def _reset_active_low(reset: Reset) -> bool:
    return reset.active == "low"


def emit_verilog(compiled: CompiledDesign) -> str:
    lines: list[str] = []
    design = compiled.design
    reset = design.reset
    active_low = _reset_active_low(reset)

    clock_name = design.clock.signal if design.clock else "clk"
    reset_name = reset.signal
    reset_i = f"{reset_name}_i"

    # --- ports -----------------------------------------------------------------
    lines.append("// Generated by gatepack (C1). Do not edit.")
    lines.append("`timescale 1ns/1ps")
    lines.append("")

    # --- M-cell blackbox declarations (§9.4) ----------------------------------
    # ``hierarchy -check`` rejects an instantiation whose module is not part of
    # the design, so C1 declares each used M-cell as a ``(* blackbox *)`` stub.
    # The stub keeps the physical part out of ``dfflibmap``/``abc`` (it has no
    # body) while still elaborating; ``write_verilog`` drops it, so the spec and
    # implementation models read by C4 define the cell without colliding.
    for cell in _distinct_macro_cells(compiled):
        lines.extend(blackbox_module(cell).strip().splitlines())
        lines.append("")

    lines.append(_attr(compiled, "name"))
    lines.append(f"module {design.name} (")
    ports = [f"input wire {clock_name}", f"input wire {reset_name}"]
    ports += [f"input wire {name}" for name in compiled.input_names]
    ports += [f"output wire {name}" for name in compiled.output_names]
    lines.append(",\n".join(f"  {p}" for p in ports))
    lines.append(");")
    lines.append("")

    # --- input synchronisers ---------------------------------------------------
    var_map: dict[str, str] = {}
    for name in compiled.input_names:
        if compiled.input_sync[name]:
            path = f"inputs[{compiled.input_names.index(name)}]"
            lines.append(f"  // two-stage synchroniser for input {name} (§9.3)")
            lines.append(f"  {_attr(compiled, path)}")
            lines.append(f"  reg {name}_s1;")
            lines.append(f"  {_attr(compiled, path)}")
            lines.append(f"  reg {name}_s2;")
            sync_edge = f"negedge {reset_name}" if active_low else f"posedge {reset_name}"
            sync_assert = f"!{reset_name}" if active_low else reset_name
            lines.append(f"  always @(posedge {clock_name} or {sync_edge}) begin")
            lines.append(f"    if ({sync_assert}) begin")
            lines.append(f"      {name}_s1 <= 1'b0;")
            lines.append(f"      {name}_s2 <= 1'b0;")
            lines.append("    end else begin")
            lines.append(f"      {name}_s1 <= {name};")
            lines.append(f"      {name}_s2 <= {name}_s1;")
            lines.append("    end")
            lines.append("  end")
            lines.append(f"  wire {name}_i = {name}_s2;")
            var_map[name] = f"{name}_i"
        else:
            var_map[name] = name
    if compiled.input_names:
        lines.append("")

    # --- reset de-assert synchroniser -----------------------------------------
    if reset.sync_deassert:
        lines.append("  // reset: async assert, sync de-assert (§9.3)")
        lines.append(f"  {_attr(compiled, 'reset')}")
        lines.append(f"  reg {reset_name}_s1;")
        lines.append(f"  {_attr(compiled, 'reset')}")
        lines.append(f"  reg {reset_name}_s2;")
        if active_low:
            lines.append(f"  always @(posedge {clock_name} or negedge {reset_name}) begin")
            lines.append(f"    if (!{reset_name}) begin")
            lines.append(f"      {reset_name}_s1 <= 1'b0;")
            lines.append(f"      {reset_name}_s2 <= 1'b0;")
            lines.append("    end else begin")
            lines.append(f"      {reset_name}_s1 <= 1'b1;")
            lines.append(f"      {reset_name}_s2 <= {reset_name}_s1;")
            lines.append("    end")
            lines.append("  end")
        else:
            lines.append(f"  always @(posedge {clock_name} or posedge {reset_name}) begin")
            lines.append(f"    if ({reset_name}) begin")
            lines.append(f"      {reset_name}_s1 <= 1'b1;")
            lines.append(f"      {reset_name}_s2 <= 1'b1;")
            lines.append("    end else begin")
            lines.append(f"      {reset_name}_s1 <= 1'b0;")
            lines.append(f"      {reset_name}_s2 <= {reset_name}_s1;")
            lines.append("    end")
            lines.append("  end")
        lines.append(f"  wire {reset_i} = {reset_name}_s2;")
        lines.append("")
    else:
        reset_i = reset_name

    # --- named expressions -----------------------------------------------------
    for name in compiled.design.expressions:
        ast = compiled.expression_asts[name]
        lines.append(f"  {_attr(compiled, f'expressions.{name}')}")
        lines.append(
            f"  wire {name} = {expr_mod.to_verilog(ast, var_map, _state_map(compiled))};"
        )
    if compiled.design.expressions:
        lines.append("")

    var_map.update({name: name for name in compiled.design.expressions})

    # --- state register --------------------------------------------------------
    if compiled.encoding == "one_hot":
        lines.extend(_emit_one_hot_state(compiled, clock_name, reset_i, active_low, var_map))
    else:
        lines.extend(_emit_encoded_state(compiled, clock_name, reset_i, active_low, var_map))

    # --- output logic ----------------------------------------------------------
    # Provenance must ride on a named net, never on a continuous `assign`
    # (M0-FINDINGS §1).  The output port has no declaration of its own to carry
    # the attribute, so C1 emits an explicitly declared intermediate wire and a
    # bare `assign` onto the port.
    state_map = _state_map(compiled)
    for name in compiled.output_names:
        ast = compiled.output_asts[name]
        lines.append(f"  {_attr(compiled, f'output_logic.{name}')}")
        lines.append(
            f"  wire {name}_int = {expr_mod.to_verilog(ast, var_map, state_map)};"
        )
        lines.append(f"  assign {name} = {name}_int;")

    # --- macros (§9.4): a real instantiation, not a comment -------------------
    # The macro is wired to the design clock, the design reset, its declared
    # enable, and its output (an internal net carrying the gp_src provenance so
    # §15.1 survives).  The behavioural meaning of the macro is supplied by C4's
    # models — the spec model on the golden side, the implementation model on the
    # gate side — never re-derived here.
    state_map = _state_map(compiled)
    for index, macro in enumerate(compiled.design.macros):
        spec = get_spec(macro.cell)
        path = f"macros[{index}]"
        design_reset_active = "low" if active_low else "high"
        if spec.reset_active != design_reset_active:
            raise CompileError(
                f"macro {macro.instance!r} ({macro.cell}) resets {spec.reset_active}; "
                f"the design reset is {design_reset_active} — the polarities must "
                f"match (no inverting reset buffer is emitted yet)"
            )
        q_wire = f"{macro.instance}_{spec.q_pin}"
        lines.append(f"  {_attr(compiled, path)}")
        lines.append(f"  wire [{spec.width - 1}:0] {q_wire};")
        conns: list[str] = []
        for port in spec.ports:
            if port.name == spec.clock_pin:
                conns.append(f".{port.name}({clock_name})")
            elif port.name == spec.reset_pin:
                conns.append(f".{port.name}({reset_name})")
            elif spec.enable_pin is not None and port.name == spec.enable_pin:
                conns.append(f".{port.name}({_macro_enable(compiled, index, macro, var_map, state_map)})")
            elif spec.serial_in_pin is not None and port.name == spec.serial_in_pin:
                # A synthetic tie-off: design.yaml has no serial-data field, so
                # the shift register shifts in a constant.  The macro remains a
                # verification vehicle (§9.4 M8), not a placed physical part.
                conns.append(f".{port.name}(1'b0)")
            elif port.name == spec.q_pin:
                conns.append(f".{port.name}({q_wire})")
            else:
                raise CompileError(
                    f"macro {macro.instance!r}: cannot wire port {port.name!r} "
                    f"of M-cell {macro.cell!r}"
                )
        lines.append(f"  {macro.cell} {macro.instance} ({', '.join(conns)});")

    # --- formal assertions (§11) ----------------------------------------------
    # These live INSIDE the design module, not in a wrapper, because Yosys does
    # not resolve hierarchical references: `dut.red` is silently turned into a
    # new undriven wire and the property is then checked against a free
    # variable connected to nothing (M6-FINDINGS §6). Signals must be
    # referenced where they exist.
    # `properties.sv` holds the statements themselves and is included here, so
    # there is exactly one source of truth and the artefact still exists as a
    # reviewable file in its own right.
    if compiled.design.properties:
        lines.append("")
        lines.append("`ifdef GP_FORMAL")
        lines.append('`include "properties.sv"')
        lines.append("`endif")

    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)


def _emit_one_hot_state(
    compiled: CompiledDesign,
    clock_name: str,
    reset_i: str,
    active_low: bool,
    var_map: dict[str, str],
) -> list[str]:
    lines: list[str] = []
    design = compiled.design
    lines.append("  // --- one-hot state register (§6.2): the flop output IS the state ---")

    for state in compiled.state_order:
        lines.append(f"  {_attr(compiled, 'states')}")
        lines.append(f"  reg state_{state};")

    # per-transition terms
    for index, tr in enumerate(design.transitions):
        guard = expr_mod.to_verilog(compiled.transition_guards[index], var_map, {})
        lines.append(f"  {_attr(compiled, f'transitions[{index}]')}")
        lines.append(f"  wire t_{index} = (state_{tr.from_} & {guard});")

    # next-state per target
    transitions = design.transitions
    for target in compiled.state_order:
        terms = [
            f"t_{i}"
            for i, tr in enumerate(transitions)
            if tr.to == target
        ]
        expr = " | ".join(terms) if terms else "1'b0"
        lines.append(f"  {_attr(compiled, 'states')}")
        lines.append(f"  wire next_{target} = {expr};")

    # One-hot initial state via set-via-feedback (M0-FINDINGS §6, option 2).
    # Every flop resets to 0; the all-zero (post-reset) condition feeds back to
    # set the initial state on the first clock.  This needs no set-capable flop,
    # which the shipped library does not have (DFF_S has no dual-sourced part).
    all_state = " | ".join(f"state_{s}" for s in compiled.state_order)
    lines.append(f"  {_attr(compiled, 'states')}")
    lines.append(f"  wire state_active = ({all_state});")
    lines.append(f"  {_attr(compiled, 'states')}")
    lines.append(f"  wire set_feedback = ~state_active;")

    edge = f"negedge {reset_i}" if active_low else f"posedge {reset_i}"
    assert_expr = f"!{reset_i}" if active_low else reset_i
    lines.append(f"  always @(posedge {clock_name} or {edge}) begin")
    lines.append(f"    if ({assert_expr}) begin")
    for state in compiled.state_order:
        lines.append(f"      state_{state} <= 1'b0;")
    lines.append("    end else begin")
    for state in compiled.state_order:
        if state == design.initial:
            lines.append(f"      state_{state} <= next_{state} | set_feedback;")
        else:
            lines.append(f"      state_{state} <= next_{state};")
    lines.append("    end")
    lines.append("  end")
    lines.append("")
    return lines


def _emit_encoded_state(
    compiled: CompiledDesign,
    clock_name: str,
    reset_i: str,
    active_low: bool,
    var_map: dict[str, str],
) -> list[str]:
    lines: list[str] = []
    design = compiled.design
    width = compiled.state_width
    lines.append(f"  // --- {compiled.encoding}-encoded state register ---")

    for state in compiled.state_order:
        code = compiled.state_codes[state]
        lines.append(f"  localparam [{width - 1}:0] STATE_{state} = {width}'d{code};")

    lines.append(f"  reg [{width - 1}:0] state;")

    edge = f"negedge {reset_i}" if active_low else f"posedge {reset_i}"
    assert_expr = f"!{reset_i}" if active_low else reset_i
    init_code = compiled.state_codes[design.initial]
    lines.append(f"  always @(posedge {clock_name} or {edge}) begin")
    lines.append(f"    if ({assert_expr}) begin")
    lines.append(f"      state <= STATE_{design.initial};")
    lines.append("    end else begin")
    lines.append("      case (state)")

    grouped: dict[str, list[int]] = {}
    for index, tr in enumerate(design.transitions):
        grouped.setdefault(tr.from_, []).append(index)

    for state in compiled.state_order:
        indices = grouped.get(state, [])
        lines.append(f"        STATE_{state}: begin")
        if not indices:
            lines.append(f"          state <= state;")
        else:
            for pos, index in enumerate(indices):
                tr = design.transitions[index]
                guard = expr_mod.to_verilog(compiled.transition_guards[index], var_map, {})
                kw = "if" if pos == 0 else "else if"
                lines.append(
                    f"          {kw} ({guard}) state <= STATE_{tr.to};  "
                    f"// transitions[{index}]"
                )
            lines.append(f"          else state <= state;")
        lines.append("        end")
    lines.append("        default: state <= STATE_" + design.initial + ";")
    lines.append("      endcase")
    lines.append("    end")
    lines.append("  end")
    lines.append("")
    return lines


def _state_map(compiled: CompiledDesign) -> dict[str, str]:
    if compiled.encoding == "one_hot":
        return {s: f"state_{s}" for s in compiled.state_order}
    return {s: f"(state == STATE_{s})" for s in compiled.state_order}


def _distinct_macro_cells(compiled: CompiledDesign) -> list[str]:
    """M-cell names used by the design, in first-use order, without duplicates."""
    cells: list[str] = []
    for macro in compiled.design.macros:
        if macro.cell not in cells:
            cells.append(macro.cell)
    return cells


def _macro_enable(
    compiled: CompiledDesign,
    index: int,
    macro,
    var_map: dict[str, str],
    state_map: dict[str, str],
) -> str:
    """The Verilog expression driving a macro's enable pin (``1'b1`` if unset)."""
    ast = compiled.macro_enable_asts[index]
    if ast is None:
        return "1'b1"
    return expr_mod.to_verilog(ast, var_map, state_map)


# Reset must be held long enough to traverse the two-flop reset
# de-assert synchroniser (§9.6) and load the state flops. A one-cycle
# assertion never reaches them — M6-FINDINGS §2.1.
_RESET_HOLD_CYCLES = 4


def emit_properties(compiled: CompiledDesign) -> str:
    r"""Emit ``properties.sv`` (§11) — compiled at M2, discharged by sby at M6.

    This file holds **statements, not a module**. It is ``\`include``d into the
    design module by ``emit_verilog`` under ``\`ifdef GP_FORMAL``.

    That structure is forced by measurement, not preference. A wrapper module
    instantiating the design cannot see the design's signals: Yosys does not
    resolve ``dut.<signal>``, it implicitly declares a new **undriven** wire of
    that name, and the property is then checked against a free variable
    connected to nothing (M6-FINDINGS §6). Assertions must be emitted in the
    scope where the signals they name actually exist.
    """
    design = compiled.design
    reset = design.reset
    active_low = _reset_active_low(reset)
    clock_name = design.clock.signal if design.clock else "clk"
    reset_name = reset.signal
    # `reset_held` is true while reset is ASSERTED; `reset_released` is its
    # complement, and replaces SVA's `disable iff`.
    reset_held = f"!{reset_name}" if active_low else reset_name
    reset_released = reset_name if active_low else f"!{reset_name}"

    lines: list[str] = []
    lines.append("// Generated by gatepack (C1). Discharged by sby (M6).")
    lines.append("//")
    lines.append("// Statements only - no module. `include`d into the design")
    lines.append("// module under `ifdef GP_FORMAL, because a wrapper cannot")
    lines.append("// reference the design's internals (M6-FINDINGS §6).")
    lines.append("")

    # M6-FINDINGS §2: a formal engine starts from a completely unconstrained
    # state, so without this a register can begin in a state the circuit can
    # never reach after reset and a *true* invariant fails at step 1. The hold
    # is not one cycle: reset de-asserts through a two-flop synchroniser
    # (§9.6), so a single-cycle reset never reaches the state flops at all.
    lines.append("  // Reset assumption (M6-FINDINGS §2). Without it every")
    lines.append("  // property fails from states the circuit cannot be in.")
    lines.append(f"  localparam GP_RESET_CYCLES = {_RESET_HOLD_CYCLES};")
    lines.append("  reg [3:0] gp_cycle = 4'd0;")
    lines.append(
        f"  always @(posedge {clock_name}) if (gp_cycle != 4'd15) gp_cycle <= gp_cycle + 4'd1;"
    )
    lines.append(
        f"  always @(posedge {clock_name}) "
        f"if (gp_cycle < GP_RESET_CYCLES) assume ({reset_held});"
    )
    lines.append("  wire gp_settled = (gp_cycle >= GP_RESET_CYCLES);")
    lines.append("")

    for index, prop in enumerate(design.properties):
        assert_label = property_assert_label(index)
        lines.append(f"  // {prop.kind}: {prop.name}")

        if prop.kind in ("invariant", "mutex"):
            body = _property_body(compiled, prop.expr or "1")
            covers = property_cover_specs(compiled, index, prop)
            # M6-FINDINGS §1: immediate assertions in a clocked always block.
            # Open-source Yosys cannot parse SVA concurrent assertions.
            #
            # Asserts and covers are separated by `ifdef because `mode cover`
            # still *checks* assertions: an antecedent cover whose trace must
            # pass through the very state the assertion forbids (the
            # property-violating golden) would otherwise make the cover report
            # FAIL for a reason that has nothing to do with reachability. The
            # prove task reads the file with -DGP_PROVE (asserts only); the
            # cover task with -DGP_COVER (covers only).
            lines.append("`ifdef GP_COVER")
            lines.append(f"  always @(posedge {clock_name}) begin")
            lines.append(f"    if (gp_settled && {reset_released}) begin")
            for spec in covers:
                lines.append(f"      // vacuity guard: {spec.description}")
                lines.append(f"      {spec.label}: cover ({spec.expr});")
            lines.append("    end")
            lines.append("  end")
            lines.append("`endif")
            lines.append("`ifdef GP_PROVE")
            lines.append(f"  always @(posedge {clock_name}) begin")
            lines.append(f"    if (gp_settled && {reset_released})")
            lines.append(f"      {assert_label}: assert ({body});")
            lines.append("  end")
            lines.append("`endif")
        elif prop.kind == "reachability":
            spec = property_cover_specs(compiled, index, prop)[0]
            lines.append(
                f"  // cover (BMC target): can {prop.to} be reached from {prop.from_}? "
                f"(from-state assumption: {prop.from_})"
            )
            lines.append("`ifdef GP_COVER")
            lines.append(f"  always @(posedge {clock_name}) begin")
            lines.append(f"    if (gp_settled && {reset_released})")
            lines.append(f"      {spec.label}: cover ({spec.expr});")
            lines.append("  end")
            lines.append("`endif")
        else:  # liveness
            spec = property_cover_specs(compiled, index, prop)[0]
            lines.append(
                f"  // liveness as bounded reachability (§21.5): {spec.description}. "
                f"Bound = default_depth (max(2*state_count, 64)); the result is always "
                f"reported as bounded, never as passed."
            )
            lines.append("`ifdef GP_COVER")
            lines.append(f"  always @(posedge {clock_name}) begin")
            lines.append(f"    if (gp_settled && {reset_released})")
            lines.append(f"      {spec.label}: cover ({spec.expr});")
            lines.append("  end")
            lines.append("`endif")
        lines.append("")

    return "\n".join(lines)


def property_assert_label(index: int) -> str:
    """Label for a property's assertion. sby reports failures by this name."""
    return f"gp_assert_{index}"


@dataclass(frozen=True)
class CoverSpec:
    """One cover statement for a property — the §11 vacuity guard, or a bounded
    reachability/liveness target.

    ``expr`` is the in-module Verilog expression to cover; ``description`` is the
    human-readable account of what reaching the cover establishes, surfaced in the
    report ("signal 'red' asserted", "state 'IDLE' entered", ...).
    """

    label: str
    expr: str
    description: str


def property_cover_specs(
    compiled: CompiledDesign, index: int, prop
) -> list[CoverSpec]:
    """The cover statements for property ``index``.

    This is the anti-vacuity spine, and it deliberately does **not** cover the
    property body. A body cover is close to useless: ``!(a & b) & !(b & c)`` is
    satisfied by the all-zero state, so reaching it proves nothing about whether
    the interesting case ever occurs. What a guard must establish is that the
    property's *antecedent* — the situation it constrains — is actually
    reachable:

    * ``mutex`` over signals a, b, c: one cover per signal, each individually
      assertable. A mutex over signals that never go high is vacuously true and
      is reported as such (an unreached cover is a failure, never a pass).
    * ``invariant`` of implication form (``p -> q``, spelled ``!p | q`` or
      ``!(p & !q)``): cover ``p``.
    * ``invariant`` with no obvious antecedent: cover each referenced signal,
      and name what was covered in the report.
    * ``reachability`` / ``liveness``: one cover of the target (bounded, §21.5).

    Referenced signals are extracted from the expression AST
    (:mod:`gatepack.frontend.expr`), never by pattern-matching the source string.
    """
    if prop.kind == "invariant":
        return _invariant_covers(compiled, index, prop)
    if prop.kind == "mutex":
        return _signal_covers(compiled, index, prop)
    if prop.kind == "reachability":
        target = _property_body(compiled, _state_eq(prop.to or ""))
        return [
            CoverSpec(
                f"gp_cover_{index}",
                target,
                f"state {prop.to!r} reachable from {prop.from_!r}",
            )
        ]
    if prop.kind == "liveness":
        return [
            CoverSpec(
                f"gp_cover_{index}",
                _liveness_target(compiled, prop),
                f"liveness target {_liveness_target_desc(prop)!r} reachable "
                f"within the §21.5 bound",
            )
        ]
    return []


def _invariant_covers(
    compiled: CompiledDesign, index: int, prop
) -> list[CoverSpec]:
    ast = _parse_prop_expr(prop.expr)
    if ast is not None:
        antecedent = _implication_antecedent(ast)
        if antecedent is not None:
            expr = expr_mod.to_verilog(
                antecedent, _property_var_map(compiled), _state_map(compiled)
            )
            return [
                CoverSpec(
                    f"gp_cover_{index}",
                    expr,
                    "implication antecedent (p in p -> q)",
                )
            ]
    return _signal_covers(compiled, index, prop)


def _signal_covers(
    compiled: CompiledDesign, index: int, prop
) -> list[CoverSpec]:
    ast = _parse_prop_expr(prop.expr)
    subjects: list[tuple[str, str]] = []
    if ast is not None:
        var_map = _property_var_map(compiled)
        state_map = _state_map(compiled)
        for name in sorted(expr_mod.free_vars(ast)):
            subjects.append((var_map.get(name, name), f"signal {name!r} asserted"))
        for state in sorted(expr_mod.states_referenced(ast)):
            subjects.append((state_map[state], f"state {state!r} entered"))
    labels = _cover_labels(index, len(subjects))
    return [
        CoverSpec(label, verilog, desc)
        for label, (verilog, desc) in zip(labels, subjects)
    ]


def _cover_labels(index: int, count: int) -> list[str]:
    if count == 1:
        return [f"gp_cover_{index}"]
    return [f"gp_cover_{index}_{j}" for j in range(count)]


def _parse_prop_expr(text: str | None):
    if not text:
        return None
    try:
        return expr_mod.parse(text)
    except expr_mod.ExprError:
        return None


def _implication_antecedent(ast):
    # p -> q, spelled !p | q (OR is commutative, so also q | !p).
    if isinstance(ast, expr_mod.Bin) and ast.op == "|":
        if isinstance(ast.left, expr_mod.Not) and not isinstance(
            ast.right, expr_mod.Not
        ):
            return ast.left.x
        if isinstance(ast.right, expr_mod.Not) and not isinstance(
            ast.left, expr_mod.Not
        ):
            return ast.right.x
    # p -> q, spelled !(p & !q) (& is commutative, so also !(!q & p)).
    if (
        isinstance(ast, expr_mod.Not)
        and isinstance(ast.x, expr_mod.Bin)
        and ast.x.op == "&"
    ):
        if isinstance(ast.x.left, expr_mod.Not) and not isinstance(
            ast.x.right, expr_mod.Not
        ):
            return ast.x.right
        if isinstance(ast.x.right, expr_mod.Not) and not isinstance(
            ast.x.left, expr_mod.Not
        ):
            return ast.x.left
    return None


def _liveness_target(compiled: CompiledDesign, prop) -> str:
    if prop.to:
        return _property_body(compiled, _state_eq(prop.to))
    ast = _parse_prop_expr(prop.expr)
    if ast is not None:
        return expr_mod.to_verilog(
            ast, _property_var_map(compiled), _state_map(compiled)
        )
    # A prose liveness expression (e.g. "all states reach IDLE") is not a
    # parseable target. Degenerate to a trivially-reachable cover rather than
    # emit Verilog that will not parse (recorded in BUILD-NOTES).
    return "1"


def _liveness_target_desc(prop) -> str:
    return prop.to or prop.expr or "1"


def _property_var_map(compiled: CompiledDesign) -> dict[str, str]:
    var_map = {name: name for name in compiled.input_names}
    var_map.update({name: name for name in compiled.design.expressions})
    var_map.update({name: name for name in compiled.output_names})
    return var_map


def _property_body(compiled: CompiledDesign, text: str) -> str:
    try:
        ast = expr_mod.parse(text)
    except expr_mod.ExprError:
        return text
    # Plain, in-module names. Never `dut.<signal>` — Yosys does not resolve a
    # hierarchical reference, it implicitly declares a new undriven wire of
    # that name and the property is checked against nothing (M6-FINDINGS §6).
    return expr_mod.to_verilog(ast, _property_var_map(compiled), _state_map(compiled))


def _state_eq(state: str) -> str:
    return f"state == {state}" if state else "1"
