"""Behavioural Verilog + properties emission (C1, §12 C1, §15.1).

Every construct carries a ``(* gp_src = "design.yaml:<line>:<path>" *)`` attribute
— the provenance spine of §15.1.  The attribute is deliberately **not** called
``src``: Yosys populates ``src`` itself with the Verilog file/line that created
each cell and its value wins over an emitted one (M0-FINDINGS §2).

Provenance rides on **named nets**, never on cells and never on a continuous
``assign`` (M0-FINDINGS §1, §3).  Every attribute is attached to the ``wire`` or
``reg`` *declaration* of the net it describes; where a construct has no
declaration of its own (the output logic), C1 emits an explicitly declared
intermediate wire so the provenance is not dropped.  Net attributes survive
``abc`` intact, which is what makes the §15.1 spine work at all for
combinational logic.

Encoding:

* ``one_hot`` (default) — one register bit per state named ``state_<NAME>``; the
  next-state term for each transition is a named wire ``t_<index>`` carrying the
  transition's own ``gp_src`` attribute, so provenance survives into the netlist.
  The initial state is realised as **set-via-feedback** on a reset-to-0 flop
  (M0-FINDINGS §6): every state flop resets to 0, and the all-zero condition
  feeds back to set the initial state, so no set-capable flop (``DFF_S``) is
  required.
* ``binary`` / ``gray`` — a ``state`` vector with ``STATE_<NAME>`` localparams and
  a ``case`` next-state block.
"""

from __future__ import annotations

from gatepack.frontend import expr as expr_mod
from gatepack.frontend.model import CompiledDesign
from gatepack.frontend.schema import Reset


def _attr(compiled: CompiledDesign, path: str) -> str:
    line = compiled.provenance.get(path)
    display = str(line) if line is not None else "?"
    return f'(* gp_src = "{compiled.source_name}:{display}:{path}" *)'


def _reset_active_low(reset: Reset) -> bool:
    return reset.active == "low"


def emit_verilog(compiled: CompiledDesign) -> str:
    lines: list[str] = []
    design = compiled.design
    reset = design.reset
    active_low = _reset_active_low(reset)

    clock_name = design.clock.signal if design.clock else "clk"
    reset_name = reset.signal
    reset_i = f"{reset_name}_i"

    # --- ports -----------------------------------------------------------------
    lines.append("// Generated by gatepack (C1). Do not edit.")
    lines.append("`timescale 1ns/1ps")
    lines.append("")
    lines.append(_attr(compiled, "name"))
    lines.append(f"module {design.name} (")
    ports = [f"input wire {clock_name}", f"input wire {reset_name}"]
    ports += [f"input wire {name}" for name in compiled.input_names]
    ports += [f"output wire {name}" for name in compiled.output_names]
    lines.append(",\n".join(f"  {p}" for p in ports))
    lines.append(");")
    lines.append("")

    # --- input synchronisers ---------------------------------------------------
    var_map: dict[str, str] = {}
    for name in compiled.input_names:
        if compiled.input_sync[name]:
            path = f"inputs[{compiled.input_names.index(name)}]"
            lines.append(f"  // two-stage synchroniser for input {name} (§9.3)")
            lines.append(f"  {_attr(compiled, path)}")
            lines.append(f"  reg {name}_s1;")
            lines.append(f"  {_attr(compiled, path)}")
            lines.append(f"  reg {name}_s2;")
            sync_edge = f"negedge {reset_name}" if active_low else f"posedge {reset_name}"
            sync_assert = f"!{reset_name}" if active_low else reset_name
            lines.append(f"  always @(posedge {clock_name} or {sync_edge}) begin")
            lines.append(f"    if ({sync_assert}) begin")
            lines.append(f"      {name}_s1 <= 1'b0;")
            lines.append(f"      {name}_s2 <= 1'b0;")
            lines.append("    end else begin")
            lines.append(f"      {name}_s1 <= {name};")
            lines.append(f"      {name}_s2 <= {name}_s1;")
            lines.append("    end")
            lines.append("  end")
            lines.append(f"  wire {name}_i = {name}_s2;")
            var_map[name] = f"{name}_i"
        else:
            var_map[name] = name
    if compiled.input_names:
        lines.append("")

    # --- reset de-assert synchroniser -----------------------------------------
    if reset.sync_deassert:
        lines.append("  // reset: async assert, sync de-assert (§9.3)")
        lines.append(f"  {_attr(compiled, 'reset')}")
        lines.append(f"  reg {reset_name}_s1;")
        lines.append(f"  {_attr(compiled, 'reset')}")
        lines.append(f"  reg {reset_name}_s2;")
        if active_low:
            lines.append(f"  always @(posedge {clock_name} or negedge {reset_name}) begin")
            lines.append(f"    if (!{reset_name}) begin")
            lines.append(f"      {reset_name}_s1 <= 1'b0;")
            lines.append(f"      {reset_name}_s2 <= 1'b0;")
            lines.append("    end else begin")
            lines.append(f"      {reset_name}_s1 <= 1'b1;")
            lines.append(f"      {reset_name}_s2 <= {reset_name}_s1;")
            lines.append("    end")
            lines.append("  end")
        else:
            lines.append(f"  always @(posedge {clock_name} or posedge {reset_name}) begin")
            lines.append(f"    if ({reset_name}) begin")
            lines.append(f"      {reset_name}_s1 <= 1'b1;")
            lines.append(f"      {reset_name}_s2 <= 1'b1;")
            lines.append("    end else begin")
            lines.append(f"      {reset_name}_s1 <= 1'b0;")
            lines.append(f"      {reset_name}_s2 <= {reset_name}_s1;")
            lines.append("    end")
            lines.append("  end")
        lines.append(f"  wire {reset_i} = {reset_name}_s2;")
        lines.append("")
    else:
        reset_i = reset_name

    # --- named expressions -----------------------------------------------------
    for name in compiled.design.expressions:
        ast = compiled.expression_asts[name]
        lines.append(f"  {_attr(compiled, f'expressions.{name}')}")
        lines.append(
            f"  wire {name} = {expr_mod.to_verilog(ast, var_map, _state_map(compiled))};"
        )
    if compiled.design.expressions:
        lines.append("")

    var_map.update({name: name for name in compiled.design.expressions})

    # --- state register --------------------------------------------------------
    if compiled.encoding == "one_hot":
        lines.extend(_emit_one_hot_state(compiled, clock_name, reset_i, active_low, var_map))
    else:
        lines.extend(_emit_encoded_state(compiled, clock_name, reset_i, active_low, var_map))

    # --- output logic ----------------------------------------------------------
    # Provenance must ride on a named net, never on a continuous `assign`
    # (M0-FINDINGS §1).  The output port has no declaration of its own to carry
    # the attribute, so C1 emits an explicitly declared intermediate wire and a
    # bare `assign` onto the port.
    state_map = _state_map(compiled)
    for name in compiled.output_names:
        ast = compiled.output_asts[name]
        lines.append(f"  {_attr(compiled, f'output_logic.{name}')}")
        lines.append(
            f"  wire {name}_int = {expr_mod.to_verilog(ast, var_map, state_map)};"
        )
        lines.append(f"  assign {name} = {name}_int;")

    # --- macros (behavioural models are an M8 deliverable) ---------------------
    for macro in compiled.design.macros:
        path = f"macros[{compiled.design.macros.index(macro)}]"
        enable = f", enable {macro.enable!r}" if macro.enable else ""
        lines.append(
            f"  {_attr(compiled, path)}"
        )
        lines.append(
            f"  // M-cell {macro.instance}: {macro.cell} (clock {macro.clock}{enable}); "
            f"behavioural model emitted at M8 (gatepack/macros/cells_sim.v)."
        )

    # --- formal assertions (§11) ----------------------------------------------
    # These live INSIDE the design module, not in a wrapper, because Yosys does
    # not resolve hierarchical references: `dut.red` is silently turned into a
    # new undriven wire and the property is then checked against a free
    # variable connected to nothing (M6-FINDINGS §6). Signals must be
    # referenced where they exist.
    # `properties.sv` holds the statements themselves and is included here, so
    # there is exactly one source of truth and the artefact still exists as a
    # reviewable file in its own right.
    if compiled.design.properties:
        lines.append("")
        lines.append("`ifdef GP_FORMAL")
        lines.append('`include "properties.sv"')
        lines.append("`endif")

    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)


def _emit_one_hot_state(
    compiled: CompiledDesign,
    clock_name: str,
    reset_i: str,
    active_low: bool,
    var_map: dict[str, str],
) -> list[str]:
    lines: list[str] = []
    design = compiled.design
    lines.append("  // --- one-hot state register (§6.2): the flop output IS the state ---")

    for state in compiled.state_order:
        lines.append(f"  {_attr(compiled, 'states')}")
        lines.append(f"  reg state_{state};")

    # per-transition terms
    for index, tr in enumerate(design.transitions):
        guard = expr_mod.to_verilog(compiled.transition_guards[index], var_map, {})
        lines.append(f"  {_attr(compiled, f'transitions[{index}]')}")
        lines.append(f"  wire t_{index} = (state_{tr.from_} & {guard});")

    # next-state per target
    transitions = design.transitions
    for target in compiled.state_order:
        terms = [
            f"t_{i}"
            for i, tr in enumerate(transitions)
            if tr.to == target
        ]
        expr = " | ".join(terms) if terms else "1'b0"
        lines.append(f"  {_attr(compiled, 'states')}")
        lines.append(f"  wire next_{target} = {expr};")

    # One-hot initial state via set-via-feedback (M0-FINDINGS §6, option 2).
    # Every flop resets to 0; the all-zero (post-reset) condition feeds back to
    # set the initial state on the first clock.  This needs no set-capable flop,
    # which the shipped library does not have (DFF_S has no dual-sourced part).
    all_state = " | ".join(f"state_{s}" for s in compiled.state_order)
    lines.append(f"  {_attr(compiled, 'states')}")
    lines.append(f"  wire state_active = ({all_state});")
    lines.append(f"  {_attr(compiled, 'states')}")
    lines.append(f"  wire set_feedback = ~state_active;")

    edge = f"negedge {reset_i}" if active_low else f"posedge {reset_i}"
    assert_expr = f"!{reset_i}" if active_low else reset_i
    lines.append(f"  always @(posedge {clock_name} or {edge}) begin")
    lines.append(f"    if ({assert_expr}) begin")
    for state in compiled.state_order:
        lines.append(f"      state_{state} <= 1'b0;")
    lines.append("    end else begin")
    for state in compiled.state_order:
        if state == design.initial:
            lines.append(f"      state_{state} <= next_{state} | set_feedback;")
        else:
            lines.append(f"      state_{state} <= next_{state};")
    lines.append("    end")
    lines.append("  end")
    lines.append("")
    return lines


def _emit_encoded_state(
    compiled: CompiledDesign,
    clock_name: str,
    reset_i: str,
    active_low: bool,
    var_map: dict[str, str],
) -> list[str]:
    lines: list[str] = []
    design = compiled.design
    width = compiled.state_width
    lines.append(f"  // --- {compiled.encoding}-encoded state register ---")

    for state in compiled.state_order:
        code = compiled.state_codes[state]
        lines.append(f"  localparam [{width - 1}:0] STATE_{state} = {width}'d{code};")

    lines.append(f"  reg [{width - 1}:0] state;")

    edge = f"negedge {reset_i}" if active_low else f"posedge {reset_i}"
    assert_expr = f"!{reset_i}" if active_low else reset_i
    init_code = compiled.state_codes[design.initial]
    lines.append(f"  always @(posedge {clock_name} or {edge}) begin")
    lines.append(f"    if ({assert_expr}) begin")
    lines.append(f"      state <= STATE_{design.initial};")
    lines.append("    end else begin")
    lines.append("      case (state)")

    grouped: dict[str, list[int]] = {}
    for index, tr in enumerate(design.transitions):
        grouped.setdefault(tr.from_, []).append(index)

    for state in compiled.state_order:
        indices = grouped.get(state, [])
        lines.append(f"        STATE_{state}: begin")
        if not indices:
            lines.append(f"          state <= state;")
        else:
            for pos, index in enumerate(indices):
                tr = design.transitions[index]
                guard = expr_mod.to_verilog(compiled.transition_guards[index], var_map, {})
                kw = "if" if pos == 0 else "else if"
                lines.append(
                    f"          {kw} ({guard}) state <= STATE_{tr.to};  "
                    f"// transitions[{index}]"
                )
            lines.append(f"          else state <= state;")
        lines.append("        end")
    lines.append("        default: state <= STATE_" + design.initial + ";")
    lines.append("      endcase")
    lines.append("    end")
    lines.append("  end")
    lines.append("")
    return lines


def _state_map(compiled: CompiledDesign) -> dict[str, str]:
    if compiled.encoding == "one_hot":
        return {s: f"state_{s}" for s in compiled.state_order}
    return {s: f"(state == STATE_{s})" for s in compiled.state_order}


# Reset must be held long enough to traverse the two-flop reset
# de-assert synchroniser (§9.6) and load the state flops. A one-cycle
# assertion never reaches them — M6-FINDINGS §2.1.
_RESET_HOLD_CYCLES = 4


def emit_properties(compiled: CompiledDesign) -> str:
    r"""Emit ``properties.sv`` (§11) — compiled at M2, discharged by sby at M6.

    This file holds **statements, not a module**. It is ``\`include``d into the
    design module by ``emit_verilog`` under ``\`ifdef GP_FORMAL``.

    That structure is forced by measurement, not preference. A wrapper module
    instantiating the design cannot see the design's signals: Yosys does not
    resolve ``dut.<signal>``, it implicitly declares a new **undriven** wire of
    that name, and the property is then checked against a free variable
    connected to nothing (M6-FINDINGS §6). Assertions must be emitted in the
    scope where the signals they name actually exist.
    """
    design = compiled.design
    reset = design.reset
    active_low = _reset_active_low(reset)
    clock_name = design.clock.signal if design.clock else "clk"
    reset_name = reset.signal
    # `reset_held` is true while reset is ASSERTED; `reset_released` is its
    # complement, and replaces SVA's `disable iff`.
    reset_held = f"!{reset_name}" if active_low else reset_name
    reset_released = reset_name if active_low else f"!{reset_name}"

    lines: list[str] = []
    lines.append("// Generated by gatepack (C1). Discharged by sby (M6).")
    lines.append("//")
    lines.append("// Statements only - no module. `include`d into the design")
    lines.append("// module under `ifdef GP_FORMAL, because a wrapper cannot")
    lines.append("// reference the design's internals (M6-FINDINGS §6).")
    lines.append("")

    # M6-FINDINGS §2: a formal engine starts from a completely unconstrained
    # state, so without this a register can begin in a state the circuit can
    # never reach after reset and a *true* invariant fails at step 1. The hold
    # is not one cycle: reset de-asserts through a two-flop synchroniser
    # (§9.6), so a single-cycle reset never reaches the state flops at all.
    lines.append("  // Reset assumption (M6-FINDINGS §2). Without it every")
    lines.append("  // property fails from states the circuit cannot be in.")
    lines.append(f"  localparam GP_RESET_CYCLES = {_RESET_HOLD_CYCLES};")
    lines.append("  reg [3:0] gp_cycle = 4'd0;")
    lines.append(
        f"  always @(posedge {clock_name}) if (gp_cycle != 4'd15) gp_cycle <= gp_cycle + 4'd1;"
    )
    lines.append(
        f"  always @(posedge {clock_name}) "
        f"if (gp_cycle < GP_RESET_CYCLES) assume ({reset_held});"
    )
    lines.append("  wire gp_settled = (gp_cycle >= GP_RESET_CYCLES);")
    lines.append("")

    for index, prop in enumerate(design.properties):
        cover_label = property_cover_label(index)
        assert_label = property_assert_label(index)
        lines.append(f"  // {prop.kind}: {prop.name}")

        if prop.kind in ("invariant", "mutex"):
            body = _property_body(compiled, prop.expr or "1")
            # M6-FINDINGS §1: immediate assertions in a clocked always block.
            # Open-source Yosys cannot parse SVA concurrent assertions.
            lines.append(f"  always @(posedge {clock_name}) begin")
            lines.append("    if (gp_settled) begin")
            lines.append(f"      {cover_label}: cover ({body});")
            lines.append(f"      if ({reset_released})")
            lines.append(f"        {assert_label}: assert ({body});")
            lines.append("    end")
            lines.append("  end")
        elif prop.kind == "reachability":
            target = _property_body(compiled, _state_eq(prop.to or ""))
            lines.append(
                f"  // cover (BMC target): can {prop.to} be reached from {prop.from_}? "
                f"(from-state assumption: {prop.from_})"
            )
            lines.append(f"  always @(posedge {clock_name}) begin")
            lines.append(f"    if (gp_settled && {reset_released})")
            lines.append(f"      {cover_label}: cover ({target});")
            lines.append("  end")
        else:  # liveness
            lines.append(
                f"  // liveness '{prop.expr}' is bounded; the bound is chosen at M6 "
                f"(§21.5). Not emitted as unbounded SVA."
            )
        lines.append("")

    return "\n".join(lines)


def property_assert_label(index: int) -> str:
    """Label for a property's assertion. sby reports failures by this name."""
    return f"gp_assert_{index}"


def property_cover_label(index: int) -> str:
    """Label for a property's antecedent cover — the §11 vacuity guard."""
    return f"gp_cover_{index}"


def _property_body(compiled: CompiledDesign, text: str) -> str:
    try:
        ast = expr_mod.parse(text)
    except expr_mod.ExprError:
        return text
    # Plain, in-module names. Never `dut.<signal>` — Yosys does not resolve a
    # hierarchical reference, it implicitly declares a new undriven wire of
    # that name and the property is checked against nothing (M6-FINDINGS §6).
    var_map = {name: name for name in compiled.input_names}
    var_map.update({name: name for name in compiled.design.expressions})
    var_map.update({name: name for name in compiled.output_names})
    return expr_mod.to_verilog(ast, var_map, _state_map(compiled))


def _state_eq(state: str) -> str:
    return f"state == {state}" if state else "1"
