/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

module property_violating(clk, rst_n, x, enable, fault);
  wire _0_;
  wire _1_;
  input clk;
  wire clk;
  output enable;
  wire enable;
  wire enable_int;
  output fault;
  wire fault;
  wire fault_int;
  wire next_B;
  input rst_n;
  wire rst_n;
  wire rst_n_i;
  wire rst_n_s1;
  wire rst_n_s2;
  wire state_A;
  wire state_B;
  input x;
  wire x;
  OR2 _2_ (
    .A(state_B),
    .B(state_A),
    .Y(_1_)
  );
  AND2 _3_ (
    .A(x),
    .B(_1_),
    .Y(next_B)
  );
  NAND2 _4_ (
    .A(x),
    .B(_1_),
    .Y(_0_)
  );
  DFF_R _5_ (
    .CK(clk),
    .D(_0_),
    .Q(state_A),
    .RST_N(rst_n_s2)
  );
  DFF_R _6_ (
    .CK(clk),
    .D(next_B),
    .Q(state_B),
    .RST_N(rst_n_s2)
  );
  DFF_R _7_ (
    .CK(clk),
    .D(1'h1),
    .Q(rst_n_s1),
    .RST_N(rst_n)
  );
  DFF_R _8_ (
    .CK(clk),
    .D(rst_n_s1),
    .Q(rst_n_s2),
    .RST_N(rst_n)
  );
  assign rst_n_i = rst_n_s2;
  assign enable = state_B;
  assign enable_int = state_B;
  assign fault = state_B;
  assign fault_int = state_B;
endmodule
