/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

module xor2(clk, rst_n, a, b, y);
  input a;
  wire a;
  input b;
  wire b;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  wire rst_n_i;
  wire rst_n_s2;
  output y;
  wire y;
  wire y_int;
  AND2 _0_ (
    .A(a),
    .B(b),
    .Y(y)
  );
  assign rst_n_i = rst_n_s2;
  assign y_int = y;
endmodule
