/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

module vacuous_mutex(clk, rst_n, x, a, b);
  wire _0_;
  wire _1_;
  output a;
  wire a;
  wire a_int;
  output b;
  wire b;
  wire b_int;
  input clk;
  wire clk;
  wire next_B;
  input rst_n;
  wire rst_n;
  wire rst_n_i;
  wire rst_n_s1;
  wire rst_n_s2;
  wire state_A;
  wire state_B;
  wire t_0;
  wire t_2;
  input x;
  wire x;
  INV _2_ (
    .A(state_B),
    .Y(_1_)
  );
  AND2 _3_ (
    .A(x),
    .B(state_A),
    .Y(next_B)
  );
  NAND2 _4_ (
    .A(_1_),
    .B(next_B),
    .Y(_0_)
  );
  DFF_R _5_ (
    .CK(clk),
    .D(_0_),
    .Q(state_A),
    .RST_N(rst_n_s2)
  );
  DFF_R _6_ (
    .CK(clk),
    .D(next_B),
    .Q(state_B),
    .RST_N(rst_n_s2)
  );
  DFF_R _7_ (
    .CK(clk),
    .D(1'h1),
    .Q(rst_n_s1),
    .RST_N(rst_n)
  );
  DFF_R _8_ (
    .CK(clk),
    .D(rst_n_s1),
    .Q(rst_n_s2),
    .RST_N(rst_n)
  );
  assign b = 1'h0;
  assign b_int = 1'h0;
  assign rst_n_i = rst_n_s2;
  assign a = state_B;
  assign t_0 = next_B;
  assign a_int = state_B;
  assign t_2 = state_B;
endmodule
