// Generated by gatepack (C1). Do not edit.
`timescale 1ns/1ps

(* gp_src = "traffic_light.yaml:1:name" *)
module traffic_light (
  input wire clk,
  input wire rst_n,
  input wire go,
  input wire emergency,
  output wire red,
  output wire green,
  output wire amber
);

  // two-stage synchroniser for input go (§9.3)
  (* gp_src = "traffic_light.yaml:12:inputs[0]" *)
  reg go_s1;
  (* gp_src = "traffic_light.yaml:12:inputs[0]" *)
  reg go_s2;
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      go_s1 <= 1'b0;
      go_s2 <= 1'b0;
    end else begin
      go_s1 <= go;
      go_s2 <= go_s1;
    end
  end
  wire go_i = go_s2;
  // two-stage synchroniser for input emergency (§9.3)
  (* gp_src = "traffic_light.yaml:13:inputs[1]" *)
  reg emergency_s1;
  (* gp_src = "traffic_light.yaml:13:inputs[1]" *)
  reg emergency_s2;
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      emergency_s1 <= 1'b0;
      emergency_s2 <= 1'b0;
    end else begin
      emergency_s1 <= emergency;
      emergency_s2 <= emergency_s1;
    end
  end
  wire emergency_i = emergency_s2;

  // reset: async assert, sync de-assert (§9.3)
  (* gp_src = "traffic_light.yaml:5:reset" *)
  reg rst_n_s1;
  (* gp_src = "traffic_light.yaml:5:reset" *)
  reg rst_n_s2;
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rst_n_s1 <= 1'b0;
      rst_n_s2 <= 1'b0;
    end else begin
      rst_n_s1 <= 1'b1;
      rst_n_s2 <= rst_n_s1;
    end
  end
  wire rst_n_i = rst_n_s2;

  // --- one-hot state register (§6.2): the flop output IS the state ---
  (* gp_src = "traffic_light.yaml:19:states" *)
  reg state_RED;
  (* gp_src = "traffic_light.yaml:19:states" *)
  reg state_GREEN;
  (* gp_src = "traffic_light.yaml:19:states" *)
  reg state_AMBER;
  (* gp_src = "traffic_light.yaml:22:transitions[0]" *)
  wire t_0 = (state_RED & (go_i & (~emergency_i)));
  (* gp_src = "traffic_light.yaml:23:transitions[1]" *)
  wire t_1 = (state_RED & ((~go_i) | emergency_i));
  (* gp_src = "traffic_light.yaml:24:transitions[2]" *)
  wire t_2 = (state_GREEN & (go_i | emergency_i));
  (* gp_src = "traffic_light.yaml:25:transitions[3]" *)
  wire t_3 = (state_GREEN & ((~go_i) & (~emergency_i)));
  (* gp_src = "traffic_light.yaml:26:transitions[4]" *)
  wire t_4 = (state_AMBER & 1'b1);
  (* gp_src = "traffic_light.yaml:19:states" *)
  wire next_RED = t_1 | t_4;
  (* gp_src = "traffic_light.yaml:19:states" *)
  wire next_GREEN = t_0 | t_3;
  (* gp_src = "traffic_light.yaml:19:states" *)
  wire next_AMBER = t_2;
  (* gp_src = "traffic_light.yaml:19:states" *)
  wire state_active = (state_RED | state_GREEN | state_AMBER);
  (* gp_src = "traffic_light.yaml:19:states" *)
  wire set_feedback = ~state_active;
  always @(posedge clk or negedge rst_n_i) begin
    if (!rst_n_i) begin
      state_RED <= 1'b0;
      state_GREEN <= 1'b0;
      state_AMBER <= 1'b0;
    end else begin
      state_RED <= next_RED | set_feedback;
      state_GREEN <= next_GREEN;
      state_AMBER <= next_AMBER;
    end
  end

  (* gp_src = "traffic_light.yaml:28:output_logic.red" *)
  wire red_int = state_RED;
  assign red = red_int;
  (* gp_src = "traffic_light.yaml:29:output_logic.green" *)
  wire green_int = state_GREEN;
  assign green = green_int;
  (* gp_src = "traffic_light.yaml:30:output_logic.amber" *)
  wire amber_int = state_AMBER;
  assign amber = amber_int;

`ifdef GP_FORMAL
`include "properties.sv"
`endif
endmodule
