// Generated by gatepack (C1). Do not edit.
`timescale 1ns/1ps

(* gp_src = "xor2.yaml:1:name" *)
module xor2 (
  input wire clk,
  input wire rst_n,
  input wire a,
  input wire b,
  output wire y
);


  // reset: async assert, sync de-assert (§9.3)
  (* gp_src = "xor2.yaml:4:reset" *)
  reg rst_n_s1;
  (* gp_src = "xor2.yaml:4:reset" *)
  reg rst_n_s2;
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rst_n_s1 <= 1'b0;
      rst_n_s2 <= 1'b0;
    end else begin
      rst_n_s1 <= 1'b1;
      rst_n_s2 <= rst_n_s1;
    end
  end
  wire rst_n_i = rst_n_s2;

  // --- one-hot state register (§6.2): the flop output IS the state ---
  (* gp_src = "xor2.yaml:11:states" *)
  reg state_S0;
  (* gp_src = "xor2.yaml:14:transitions[0]" *)
  wire t_0 = (state_S0 & 1'b1);
  (* gp_src = "xor2.yaml:11:states" *)
  wire next_S0 = t_0;
  (* gp_src = "xor2.yaml:11:states" *)
  wire state_active = (state_S0);
  (* gp_src = "xor2.yaml:11:states" *)
  wire set_feedback = ~state_active;
  always @(posedge clk or negedge rst_n_i) begin
    if (!rst_n_i) begin
      state_S0 <= 1'b0;
    end else begin
      state_S0 <= next_S0 | set_feedback;
    end
  end

  (* gp_src = "xor2.yaml:16:output_logic.y" *)
  wire y_int = (a ^ b);
  assign y = y_int;
endmodule
