"""Tests for the CLI (gatepack.cli): lib check and lib gen."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from gatepack.cli import main

REPO = Path(__file__).resolve().parents[2]
LIBRARY_CSV = REPO / "libraries" / "74aup.csv"

_HEADER = (
    "cell,tier,family,part_suffix,equivalents,function,inputs,gates_per_pkg,"
    "package,mfrs,vcc_min,vcc_max,area,tpd_ns,iq_ua"
)


def _make_library(
    tmp_path: Path, cells: list[str], refs_cells: list[str] | None, stem: str = "parts"
) -> tuple[Path, Path]:
    csv_path = tmp_path / f"{stem}.csv"
    rows = [_HEADER]
    for cell in cells:
        rows.append(
            f'{cell},G,AUP,1G04,,!A,1,1,SOT-353,"TI;Nexperia",'
            f"0.8,3.6,1.0,4.6,0.9"
        )
    csv_path.write_text("\n".join(rows) + "\n")

    refs_path = tmp_path / f"{stem}.refs.md"
    if refs_cells is not None:
        ref_rows = [
            "| cell | datasheet | revision | table/page | electrical status |",
            "|------|-----------|----------|------------|-------------------|",
        ]
        for cell in refs_cells:
            ref_rows.append(f"| {cell} | TBD | TBD | TBD | placeholder - unverified |")
        refs_path.write_text("\n".join(ref_rows) + "\n")
    return csv_path, refs_path


def test_lib_check_passes_shipped_library():
    assert main(["lib", "check", str(LIBRARY_CSV)]) == 0


def test_lib_check_missing_citation_fails(tmp_path):
    csv_path, _ = _make_library(tmp_path, ["INV"], refs_cells=["NAND2"])
    assert main(["lib", "check", str(csv_path)]) == 1


def test_lib_check_missing_refs_file_fails(tmp_path):
    csv_path, _ = _make_library(tmp_path, ["INV"], refs_cells=None)
    assert main(["lib", "check", str(csv_path)]) == 1


def test_lib_gen_writes_expected_file(tmp_path):
    out = tmp_path / "out.lib"
    assert main(["lib", "gen", str(LIBRARY_CSV), "-o", str(out)]) == 0
    text = out.read_text()
    assert text.startswith("/* Generated by gatepack")
    assert "library (" in text
    assert "cell (DFF_SR)" in text


def test_lib_gen_excludes_single_source_by_default(tmp_path):
    out = tmp_path / "out.lib"
    main(["lib", "gen", str(LIBRARY_CSV), "-o", str(out)])
    assert "cell (DFF_S)" not in out.read_text()


def test_lib_gen_allow_single_source_includes(tmp_path):
    out = tmp_path / "out.lib"
    main(
        ["lib", "gen", str(LIBRARY_CSV), "-o", str(out), "--allow-single-source"]
    )
    assert "cell (DFF_S)" in out.read_text()


def test_cli_exit_code_via_module(tmp_path):
    out = tmp_path / "out.lib"
    proc = subprocess.run(
        [
            sys.executable, "-m", "gatepack.cli",
            "lib", "gen", str(LIBRARY_CSV), "-o", str(out),
        ],
        cwd=str(REPO),
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, proc.stderr
    assert out.exists()


def test_cli_missing_citation_exit_code_via_module(tmp_path):
    csv_path, _ = _make_library(tmp_path, ["INV"], refs_cells=[])
    proc = subprocess.run(
        [sys.executable, "-m", "gatepack.cli", "lib", "check", str(csv_path)],
        cwd=str(REPO),
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 1
    assert "missing a" in proc.stderr
