"""Tests for `gatepack analyse` — the standalone SCOAP + stuck-at summary.

The payload must degrade honestly: a directory with no mapped netlist (or no
generated library) is an explicit error, never a summary full of fabricated
zeros.  The Liberty reconstruction must recover each cell's function/inputs/tier
well enough that the dir-only SCOAP and stuck-at results agree with the full
`build`-style analysis (which uses the real parts.csv).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from gatepack.analysis.summary import (
    AnalysisUnavailableError,
    dir_only_payload,
    full_analysis_payload,
    load_parts_from_liberty,
)

LIBERTY = """/* Generated by gatepack (C2). */
library (gatepack) {
  cell (NAND2) {
    area : 1.0;
    pin(A) {
      direction : input;
      capacitance : 0.0;
    }
    pin(B) {
      direction : input;
      capacitance : 0.0;
    }
    pin(Y) {
      direction : output;
      function : "(!(A & B))";
    }
  }
  cell (DFF_R) {
    area : 1.0;
    ff (IQ, IQN) {
      next_state : "D";
      clocked_on : "CK";
      clear : "!RST_N";
    }
    pin(D) {
      direction : input;
      capacitance : 0.0;
    }
    pin(CK) {
      direction : input;
      clock : true;
    }
    pin(RST_N) {
      direction : input;
      capacitance : 0.0;
    }
    pin(Q) {
      direction : output;
      function : "IQ";
    }
  }
}
"""

MAPPED = (
    '{"modules": {"t": {'
    '"ports": {"a": {"direction": "input", "bits": [2]},'
    '          "b": {"direction": "input", "bits": [3]},'
    '          "y": {"direction": "output", "bits": [5]}},'
    '"cells": {'
    '"$1": {"type": "NAND2", "port_directions": {"A": "input", "B": "input", "Y": "output"},'
    '"connections": {"A": [2], "B": [3], "Y": [5]}}'
    "},"
    '"netnames": {"a": {"bits": [2]}, "b": {"bits": [3]}, "y": {"bits": [5]}}'
    "}}}"
)


def _build_dir(tmp_path: Path, *, mapped: bool = True, lib: bool = True) -> Path:
    out = tmp_path / "out"
    out.mkdir()
    if mapped:
        (out / "mapped.json").write_text(MAPPED)
    if lib:
        (out / "cells.lib").write_text(LIBERTY)
    (out / "generated.v").write_text("module t;\nendmodule\n")
    return out


def test_load_parts_from_liberty_recovers_function_and_inputs():
    parts = load_parts_from_liberty(LIBERTY)
    by_cell = {p.cell: p for p in parts}

    nand2 = by_cell["NAND2"]
    assert nand2.tier == "G"
    assert nand2.inputs == 2
    assert nand2.function == "(!(A & B))"
    # fields the Liberty file does not carry are honest placeholders, not guesses
    assert nand2.iq_ua is None
    assert nand2.gates_per_pkg == 1

    dff_r = by_cell["DFF_R"]
    assert dff_r.tier == "F"
    assert dff_r.inputs == 3
    assert dff_r.function is None


def test_dir_only_payload_reports_scoap_and_faults_not_zeros(tmp_path):
    out = _build_dir(tmp_path)
    payload = dir_only_payload(out)

    assert set(payload) == {"metrics", "scoap", "faults", "cpldBlockers"}
    # a real SCOAP table over the single NAND2 (a, b -> y)
    nets = {s["net"] for s in payload["scoap"]}
    assert nets == {"a", "b", "y"}
    for s in payload["scoap"]:
        assert set(s) == {"net", "controllability0", "controllability1", "observability"}
    # faults is a real classification, not the all-zeros placeholder
    assert sum(payload["faults"].values()) > 0
    # no package-count / pack-cost / static-current metrics — those need
    # parts.csv data the directory does not carry, and are never fabricated
    metric_names = {m["name"] for m in payload["metrics"]}
    assert "package count" not in metric_names
    assert "pack cost" not in metric_names
    assert "static current" not in metric_names


def test_dir_only_payload_requires_mapped_netlist(tmp_path):
    out = _build_dir(tmp_path, mapped=False)
    with pytest.raises(AnalysisUnavailableError, match="mapped netlist"):
        dir_only_payload(out)


def test_dir_only_payload_requires_library(tmp_path):
    out = _build_dir(tmp_path, lib=False)
    with pytest.raises(AnalysisUnavailableError, match="cells.lib"):
        dir_only_payload(out)


def test_full_analysis_matches_build_analysis(tmp_path):
    # The full path (design + library) re-runs the C5..C8 assembly and must agree
    # with the dir-only SCOAP/faults on the same netlist, while adding the
    # metrics only the parts.csv can supply.
    design = tmp_path / "d.yaml"
    design.write_text(
        "name: t\n"
        "timing_model: synchronous\n"
        "clock: {signal: clk, freq_hz: 1, source: OSC}\n"
        "reset: {signal: rst_n, active: low, source: SUPERVISOR}\n"
        "inputs:\n  - {name: a, sync: false}\n  - {name: b, sync: false}\n"
        "outputs:\n  - {name: y}\n"
        "states: [A]\n"
        "initial: A\n"
        "transitions:\n  - {from: A, to: A, when: \"1\"}\n"
        "output_logic: {y: \"!(a & b)\"}\n"
    )
    out = _build_dir(tmp_path)
    library = Path(__file__).resolve().parents[2] / "libraries" / "74aup.csv"

    full = full_analysis_payload(out, design, library)
    assert "package count" in {m["name"] for m in full["metrics"]}
    # SCOAP and stuck-at agree with the dir-only path on the same netlist
    only = dir_only_payload(out)
    assert full["scoap"] == only["scoap"]
    assert full["faults"] == only["faults"]
