/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

module pelican(clk, rst_n, request, hold, traffic_red, traffic_amber, traffic_green, walk);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  input clk;
  wire clk;
  input hold;
  wire hold;
  wire hold_i;
  reg hold_s1;
  reg hold_s2;
  wire next_CLEAR;
  wire next_CROSS;
  wire next_GO;
  wire next_STOP;
  wire next_WARN;
  input request;
  wire request;
  wire request_i;
  reg request_s1;
  reg request_s2;
  input rst_n;
  wire rst_n;
  wire rst_n_i;
  reg rst_n_s1;
  reg rst_n_s2;
  wire set_feedback;
  reg state_CLEAR;
  reg state_CROSS;
  reg state_GO;
  reg state_STOP;
  reg state_WARN;
  wire state_active;
  wire t_0;
  wire t_1;
  wire t_2;
  wire t_3;
  wire t_4;
  wire t_5;
  wire t_6;
  output traffic_amber;
  wire traffic_amber;
  wire traffic_amber_int;
  output traffic_green;
  wire traffic_green;
  wire traffic_green_int;
  output traffic_red;
  wire traffic_red;
  wire traffic_red_int;
  output walk;
  wire walk;
  wire walk_int;
  always @(posedge clk, negedge rst_n_s2)
    if (!rst_n_s2) state_GO <= 1'h0;
    else state_GO <= next_GO;
  always @(posedge clk, negedge rst_n_s2)
    if (!rst_n_s2) state_WARN <= 1'h0;
    else state_WARN <= next_WARN;
  always @(posedge clk, negedge rst_n_s2)
    if (!rst_n_s2) state_STOP <= 1'h0;
    else state_STOP <= _00_;
  always @(posedge clk, negedge rst_n_s2)
    if (!rst_n_s2) state_CROSS <= 1'h0;
    else state_CROSS <= next_CROSS;
  always @(posedge clk, negedge rst_n_s2)
    if (!rst_n_s2) state_CLEAR <= 1'h0;
    else state_CLEAR <= state_CROSS;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rst_n_s1 <= 1'h0;
    else rst_n_s1 <= 1'h1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rst_n_s2 <= 1'h0;
    else rst_n_s2 <= rst_n_s1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) hold_s1 <= 1'h0;
    else hold_s1 <= hold;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) hold_s2 <= 1'h0;
    else hold_s2 <= hold_s1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) request_s1 <= 1'h0;
    else request_s1 <= request;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) request_s2 <= 1'h0;
    else request_s2 <= request_s1;
  assign _03_ = ~request_s2;
  assign _02_ = ~hold_s2;
  assign set_feedback = ~state_active;
  assign _01_ = request_s2 & _02_;
  assign next_WARN = state_GO & _01_;
  assign _05_ = _03_ | hold_s2;
  assign t_1 = state_GO & _05_;
  assign next_CROSS = state_STOP & _02_;
  assign t_4 = state_STOP & hold_s2;
  assign next_GO = t_1 | state_CLEAR;
  assign next_STOP = state_WARN | t_4;
  assign _06_ = state_GO | state_WARN;
  assign _07_ = _06_ | state_STOP;
  assign _08_ = _07_ | state_CROSS;
  assign state_active = _08_ | state_CLEAR;
  assign _00_ = next_STOP | set_feedback;
  assign _04_ = state_STOP | state_CROSS;
  assign traffic_red = _04_ | state_CLEAR;
  assign hold_i = hold_s2;
  assign next_CLEAR = state_CROSS;
  assign request_i = request_s2;
  assign rst_n_i = rst_n_s2;
  assign t_0 = next_WARN;
  assign t_2 = state_WARN;
  assign t_3 = next_CROSS;
  assign t_5 = state_CROSS;
  assign t_6 = state_CLEAR;
  assign traffic_amber = state_WARN;
  assign traffic_amber_int = state_WARN;
  assign traffic_green = state_GO;
  assign traffic_green_int = state_GO;
  assign traffic_red_int = traffic_red;
  assign walk = state_CROSS;
  assign walk_int = state_CROSS;
endmodule
