// Generated by gatepack (C1). Discharged by sby (M6).
//
// Statements only - no module. `include`d into the design
// module under `ifdef GP_FORMAL, because a wrapper cannot
// reference the design's internals (M6-FINDINGS §6).

  // Reset assumption (M6-FINDINGS §2). Without it every
  // property fails from states the circuit cannot be in.
  localparam GP_RESET_CYCLES = 4;
  reg [3:0] gp_cycle = 4'd0;
  always @(posedge clk) if (gp_cycle != 4'd15) gp_cycle <= gp_cycle + 4'd1;
  always @(posedge clk) if (gp_cycle < GP_RESET_CYCLES) assume (!rst_n);
  wire gp_settled = (gp_cycle >= GP_RESET_CYCLES);

  // mutex: never_walk_with_traffic
`ifdef GP_COVER
  always @(posedge clk) begin
    if (gp_settled && rst_n) begin
      // vacuity guard: signal 'traffic_amber' asserted
      gp_cover_0_0: cover (traffic_amber);
      // vacuity guard: signal 'traffic_green' asserted
      gp_cover_0_1: cover (traffic_green);
      // vacuity guard: signal 'walk' asserted
      gp_cover_0_2: cover (walk);
    end
  end
`endif
`ifdef GP_PROVE
  always @(posedge clk) begin
    if (gp_settled && rst_n)
      gp_assert_0: assert (((~(walk & traffic_green)) & (~(walk & traffic_amber))));
  end
`endif

  // mutex: one_traffic_aspect
`ifdef GP_COVER
  always @(posedge clk) begin
    if (gp_settled && rst_n) begin
      // vacuity guard: signal 'traffic_amber' asserted
      gp_cover_1_0: cover (traffic_amber);
      // vacuity guard: signal 'traffic_green' asserted
      gp_cover_1_1: cover (traffic_green);
      // vacuity guard: signal 'traffic_red' asserted
      gp_cover_1_2: cover (traffic_red);
    end
  end
`endif
`ifdef GP_PROVE
  always @(posedge clk) begin
    if (gp_settled && rst_n)
      gp_assert_1: assert ((((~(traffic_red & traffic_green)) & (~(traffic_green & traffic_amber))) & (~(traffic_red & traffic_amber))));
  end
`endif
