// Generated by gatepack (C1). Do not edit.
`timescale 1ns/1ps

(* gp_src = "design.yaml:23:name" *)
module pelican (
  input wire clk,
  input wire rst_n,
  input wire request,
  input wire hold,
  output wire traffic_red,
  output wire traffic_amber,
  output wire traffic_green,
  output wire walk
);

  // two-stage synchroniser for input request (§9.3)
  (* gp_src = "design.yaml:43:inputs[0]" *)
  reg request_s1;
  (* gp_src = "design.yaml:43:inputs[0]" *)
  reg request_s2;
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      request_s1 <= 1'b0;
      request_s2 <= 1'b0;
    end else begin
      request_s1 <= request;
      request_s2 <= request_s1;
    end
  end
  wire request_i = request_s2;
  // two-stage synchroniser for input hold (§9.3)
  (* gp_src = "design.yaml:45:inputs[1]" *)
  reg hold_s1;
  (* gp_src = "design.yaml:45:inputs[1]" *)
  reg hold_s2;
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      hold_s1 <= 1'b0;
      hold_s2 <= 1'b0;
    end else begin
      hold_s1 <= hold;
      hold_s2 <= hold_s1;
    end
  end
  wire hold_i = hold_s2;

  // reset: async assert, sync de-assert (§9.3)
  (* gp_src = "design.yaml:31:reset" *)
  reg rst_n_s1;
  (* gp_src = "design.yaml:31:reset" *)
  reg rst_n_s2;
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rst_n_s1 <= 1'b0;
      rst_n_s2 <= 1'b0;
    end else begin
      rst_n_s1 <= 1'b1;
      rst_n_s2 <= rst_n_s1;
    end
  end
  wire rst_n_i = rst_n_s2;

  // --- one-hot state register (§6.2): the flop output IS the state ---
  (* gp_src = "design.yaml:55:states" *)
  reg state_GO;
  (* gp_src = "design.yaml:55:states" *)
  reg state_WARN;
  (* gp_src = "design.yaml:55:states" *)
  reg state_STOP;
  (* gp_src = "design.yaml:55:states" *)
  reg state_CROSS;
  (* gp_src = "design.yaml:55:states" *)
  reg state_CLEAR;
  (* gp_src = "design.yaml:60:transitions[0]" *)
  wire t_0 = (state_GO & (request_i & (~hold_i)));
  (* gp_src = "design.yaml:61:transitions[1]" *)
  wire t_1 = (state_GO & ((~request_i) | hold_i));
  (* gp_src = "design.yaml:63:transitions[2]" *)
  wire t_2 = (state_WARN & 1'b1);
  (* gp_src = "design.yaml:64:transitions[3]" *)
  wire t_3 = (state_STOP & (~hold_i));
  (* gp_src = "design.yaml:65:transitions[4]" *)
  wire t_4 = (state_STOP & hold_i);
  (* gp_src = "design.yaml:67:transitions[5]" *)
  wire t_5 = (state_CROSS & 1'b1);
  (* gp_src = "design.yaml:68:transitions[6]" *)
  wire t_6 = (state_CLEAR & 1'b1);
  (* gp_src = "design.yaml:55:states" *)
  wire next_GO = t_1 | t_6;
  (* gp_src = "design.yaml:55:states" *)
  wire next_WARN = t_0;
  (* gp_src = "design.yaml:55:states" *)
  wire next_STOP = t_2 | t_4;
  (* gp_src = "design.yaml:55:states" *)
  wire next_CROSS = t_3;
  (* gp_src = "design.yaml:55:states" *)
  wire next_CLEAR = t_5;
  (* gp_src = "design.yaml:55:states" *)
  wire state_active = (state_GO | state_WARN | state_STOP | state_CROSS | state_CLEAR);
  (* gp_src = "design.yaml:55:states" *)
  wire set_feedback = ~state_active;
  always @(posedge clk or negedge rst_n_i) begin
    if (!rst_n_i) begin
      state_GO <= 1'b0;
      state_WARN <= 1'b0;
      state_STOP <= 1'b0;
      state_CROSS <= 1'b0;
      state_CLEAR <= 1'b0;
    end else begin
      state_GO <= next_GO;
      state_WARN <= next_WARN;
      state_STOP <= next_STOP | set_feedback;
      state_CROSS <= next_CROSS;
      state_CLEAR <= next_CLEAR;
    end
  end

  (* gp_src = "design.yaml:74:output_logic.traffic_red" *)
  wire traffic_red_int = ((state_STOP | state_CROSS) | state_CLEAR);
  assign traffic_red = traffic_red_int;
  (* gp_src = "design.yaml:75:output_logic.traffic_amber" *)
  wire traffic_amber_int = state_WARN;
  assign traffic_amber = traffic_amber_int;
  (* gp_src = "design.yaml:76:output_logic.traffic_green" *)
  wire traffic_green_int = state_GO;
  assign traffic_green = traffic_green_int;
  (* gp_src = "design.yaml:77:output_logic.walk" *)
  wire walk_int = state_CROSS;
  assign walk = walk_int;

`ifdef GP_FORMAL
`include "properties.sv"
`endif
endmodule
